//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES20
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "TextureBorderClamp" in the extension "Oes".
        /// </summary>
        public static partial class Oes
        {
            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetSamplerParameterIivOES")]
            public static void GetSamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetSamplerParameterIivOES")]
            public static void GetSamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetSamplerParameterIivOES")]
            public static unsafe void GetSamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetSamplerParameterIuivOES")]
            public static void GetSamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetSamplerParameterIuivOES")]
            public static void GetSamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] out uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetSamplerParameterIuivOES")]
            public static unsafe void GetSamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetTexParameterIivOES")]
            public static void GetTexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetTexParameterIivOES")]
            public static void GetTexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetTexParameterIivOES")]
            public static unsafe void GetTexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetTexParameterIuivOES")]
            public static void GetTexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetTexParameterIuivOES")]
            public static void GetTexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] out uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glGetTexParameterIuivOES")]
            public static unsafe void GetTexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glSamplerParameterIivOES")]
            public static void SamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] int[] param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glSamplerParameterIivOES")]
            public static void SamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] ref int param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glSamplerParameterIivOES")]
            public static unsafe void SamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] int* param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glSamplerParameterIuivOES")]
            public static void SamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] uint[] param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glSamplerParameterIuivOES")]
            public static void SamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] ref uint param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="sampler">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glSamplerParameterIuivOES")]
            public static unsafe void SamplerParameterI(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] uint* param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glTexParameterIivOES")]
            public static void TexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glTexParameterIivOES")]
            public static void TexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glTexParameterIivOES")]
            public static unsafe void TexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glTexParameterIuivOES")]
            public static void TexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glTexParameterIuivOES")]
            public static void TexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] ref uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_texture_border_clamp]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "OES_texture_border_clamp", Version = "", EntryPoint = "glTexParameterIuivOES")]
            public static unsafe void TexParameterI(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(289)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetSamplerParameterIivOES(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params);

            [Slot(291)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetSamplerParameterIuivOES(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [OutAttribute, CountAttribute(Computed = "pname")] uint* @params);

            [Slot(301)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetTexParameterIivOES(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params);

            [Slot(303)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetTexParameterIuivOES(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.GetTextureParameter pname, [OutAttribute, CountAttribute(Computed = "pname")] uint* @params);

            [Slot(512)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glSamplerParameterIivOES(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] int* param);

            [Slot(514)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glSamplerParameterIuivOES(uint sampler, OpenTK.Graphics.ES20.SamplerParameterName pname, [CountAttribute(Computed = "pname")] uint* param);

            [Slot(558)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexParameterIivOES(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] int* @params);

            [Slot(560)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexParameterIuivOES(OpenTK.Graphics.ES20.TextureTarget target, OpenTK.Graphics.ES20.TextureParameterName pname, [CountAttribute(Computed = "pname")] uint* @params);
        }
    }
}
