//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES31
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "Robustness" in the extension "Khr".
        /// </summary>
        public static partial class Khr
        {
            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetGraphicsResetStatusKHR")]
            public static OpenTK.Graphics.ES31.GraphicsResetStatus GetGraphicsResetStatus()
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformfvKHR")]
            public static void GetnUniform(uint program, int location, int bufSize, [OutAttribute] float[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformfvKHR")]
            public static void GetnUniform(uint program, int location, int bufSize, [OutAttribute] out float @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformfvKHR")]
            public static unsafe void GetnUniform(uint program, int location, int bufSize, [OutAttribute] float* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformivKHR")]
            public static void GetnUniform(uint program, int location, int bufSize, [OutAttribute] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformivKHR")]
            public static void GetnUniform(uint program, int location, int bufSize, [OutAttribute] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformivKHR")]
            public static unsafe void GetnUniform(uint program, int location, int bufSize, [OutAttribute] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformuivKHR")]
            public static void GetnUniform(uint program, int location, int bufSize, [OutAttribute] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformuivKHR")]
            public static void GetnUniform(uint program, int location, int bufSize, [OutAttribute] out uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="location">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="@params">
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glGetnUniformuivKHR")]
            public static unsafe void GetnUniform(uint program, int location, int bufSize, [OutAttribute] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="data">
            /// [length: bufSize]
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glReadnPixelsKHR")]
            public static void ReadnPixels(int x, int y, int width, int height, OpenTK.Graphics.ES31.PixelFormat format, OpenTK.Graphics.ES31.PixelType type, int bufSize, [OutAttribute, CountAttribute(Parameter = "bufSize")] IntPtr data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="data">
            /// [length: bufSize]
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glReadnPixelsKHR")]
            public static void ReadnPixels<T7>(int x, int y, int width, int height, OpenTK.Graphics.ES31.PixelFormat format, OpenTK.Graphics.ES31.PixelType type, int bufSize, [InAttribute, OutAttribute, CountAttribute(Parameter = "bufSize")] T7[] data)
                where T7 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="data">
            /// [length: bufSize]
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glReadnPixelsKHR")]
            public static void ReadnPixels<T7>(int x, int y, int width, int height, OpenTK.Graphics.ES31.PixelFormat format, OpenTK.Graphics.ES31.PixelType type, int bufSize, [InAttribute, OutAttribute, CountAttribute(Parameter = "bufSize")] T7[,] data)
                where T7 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="data">
            /// [length: bufSize]
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glReadnPixelsKHR")]
            public static void ReadnPixels<T7>(int x, int y, int width, int height, OpenTK.Graphics.ES31.PixelFormat format, OpenTK.Graphics.ES31.PixelType type, int bufSize, [InAttribute, OutAttribute, CountAttribute(Parameter = "bufSize")] T7[,,] data)
                where T7 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: KHR_robustness]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="bufSize">
            /// </param>
            /// <param name="data">
            /// [length: bufSize]
            /// </param>
            [AutoGenerated(Category = "KHR_robustness", Version = "", EntryPoint = "glReadnPixelsKHR")]
            public static void ReadnPixels<T7>(int x, int y, int width, int height, OpenTK.Graphics.ES31.PixelFormat format, OpenTK.Graphics.ES31.PixelType type, int bufSize, [InAttribute, OutAttribute, CountAttribute(Parameter = "bufSize")] ref T7 data)
                where T7 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(284)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern OpenTK.Graphics.ES31.GraphicsResetStatus glGetGraphicsResetStatusKHR();

            [Slot(299)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetnUniformfvKHR(uint program, int location, int bufSize, [OutAttribute] float* @params);

            [Slot(302)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetnUniformivKHR(uint program, int location, int bufSize, [OutAttribute] int* @params);

            [Slot(304)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetnUniformuivKHR(uint program, int location, int bufSize, [OutAttribute] uint* @params);

            [Slot(628)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glReadnPixelsKHR(int x, int y, int width, int height, OpenTK.Graphics.ES31.PixelFormat format, OpenTK.Graphics.ES31.PixelType type, int bufSize, [OutAttribute, CountAttribute(Parameter = "bufSize")] IntPtr data);
        }
    }
}
