image:
  - Visual Studio 2022
# FIXME: At some point we want to test our builds on Ubuntu?
#  - Ubuntu

version: 5.0.0.{build}

clone_depth: 1 # we only care about the commit we are building

# Appveyor doesn't have Visual Studio 2026 images yet, so we need to download dotnet 10 ourselves...
# - Noggin_bops 2026-02-28
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '10.0.103' -InstallDir "$env:ProgramFiles\dotnet"
before_build:
  - cmd: dotnet --version

nuget:
  project_feed: true

deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/opentk-ewqv6ys6uxum/api/v2/package
    api_key:
      secure: Rh0peS8dmnflnHfB5kTlsqsR1rmibtpZ2oeaWFH90iQ=
    artifact: bin/nuget/*.nupkg

artifacts:
  - path: bin/nuget/*.nupkg
    name: OpenTK Nuget Packages

init:
  - git config --global core.autocrlf input

configuration: Release

build_script:
  - ps: ./build.ps1 RunCITests
