//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "WindowPos" in the extension "Mesa".
        /// </summary>
        public static partial class Mesa
        {
            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2dMESA")]
            public static void WindowPos2(double x, double y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2dvMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] double[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2dvMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] ref double v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2fMESA")]
            public static void WindowPos2(float x, float y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2fvMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] float[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2fvMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] ref float v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2iMESA")]
            public static void WindowPos2(int x, int y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2ivMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2ivMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2sMESA")]
            public static void WindowPos2(short x, short y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2svMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] short[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos2svMESA")]
            public static void WindowPos2([CountAttribute(Count = 2)] ref short v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3dMESA")]
            public static void WindowPos3(double x, double y, double z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3dvMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] double[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3dvMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] ref double v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3fMESA")]
            public static void WindowPos3(float x, float y, float z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3fvMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] float[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3fvMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] ref float v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3iMESA")]
            public static void WindowPos3(int x, int y, int z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3ivMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3ivMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3sMESA")]
            public static void WindowPos3(short x, short y, short z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3svMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] short[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos3svMESA")]
            public static void WindowPos3([CountAttribute(Count = 3)] ref short v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="w"></param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4dMESA")]
            public static void WindowPos4(double x, double y, double z, double w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4dvMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] double[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4dvMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] ref double v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="w"></param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4fMESA")]
            public static void WindowPos4(float x, float y, float z, float w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4fvMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] float[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4fvMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] ref float v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="w"></param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4iMESA")]
            public static void WindowPos4(int x, int y, int z, int w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4ivMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4ivMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="x">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="y">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="z">
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            /// <param name="w"></param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4sMESA")]
            public static void WindowPos4(short x, short y, short z, short w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4svMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] short[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: MESA_window_pos]
            /// Specify the raster position in window coordinates for pixel operations
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// Specify the , ,  coordinates for the raster position.
            /// </param>
            [AutoGenerated(Category = "MESA_window_pos", Version = "", EntryPoint = "glWindowPos4svMESA")]
            public static void WindowPos4([CountAttribute(Count = 4)] ref short v)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(2897)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos2dMESA(double x, double y);

            [Slot(2900)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos2dvMESA([CountAttribute(Count = 2)] double* v);

            [Slot(2903)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos2fMESA(float x, float y);

            [Slot(2906)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos2fvMESA([CountAttribute(Count = 2)] float* v);

            [Slot(2909)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos2iMESA(int x, int y);

            [Slot(2912)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos2ivMESA([CountAttribute(Count = 2)] int* v);

            [Slot(2915)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos2sMESA(short x, short y);

            [Slot(2918)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos2svMESA([CountAttribute(Count = 2)] short* v);

            [Slot(2921)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos3dMESA(double x, double y, double z);

            [Slot(2924)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos3dvMESA([CountAttribute(Count = 3)] double* v);

            [Slot(2927)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos3fMESA(float x, float y, float z);

            [Slot(2930)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos3fvMESA([CountAttribute(Count = 3)] float* v);

            [Slot(2933)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos3iMESA(int x, int y, int z);

            [Slot(2936)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos3ivMESA([CountAttribute(Count = 3)] int* v);

            [Slot(2939)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos3sMESA(short x, short y, short z);

            [Slot(2942)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos3svMESA([CountAttribute(Count = 3)] short* v);

            [Slot(2943)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos4dMESA(double x, double y, double z, double w);

            [Slot(2944)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos4dvMESA([CountAttribute(Count = 4)] double* v);

            [Slot(2945)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos4fMESA(float x, float y, float z, float w);

            [Slot(2946)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos4fvMESA([CountAttribute(Count = 4)] float* v);

            [Slot(2947)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos4iMESA(int x, int y, int z, int w);

            [Slot(2948)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos4ivMESA([CountAttribute(Count = 4)] int* v);

            [Slot(2949)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glWindowPos4sMESA(short x, short y, short z, short w);

            [Slot(2950)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glWindowPos4svMESA([CountAttribute(Count = 4)] short* v);
        }
    }
}
