//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES20
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "DrawElementsBaseVertex|OESDrawElementsBaseVertex" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int[] count, OpenTK.Graphics.ES20.DrawElementsType type, [CountAttribute(Computed = "drawcount")] IntPtr indices, int primcount, [CountAttribute(Computed = "drawcount")] int[] basevertex)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int[] count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[] indices, int primcount, [CountAttribute(Computed = "drawcount")] int[] basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int[] count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[,] indices, int primcount, [CountAttribute(Computed = "drawcount")] int[] basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int[] count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[,,] indices, int primcount, [CountAttribute(Computed = "drawcount")] int[] basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int[] count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] ref T3 indices, int primcount, [CountAttribute(Computed = "drawcount")] int[] basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] ref int count, OpenTK.Graphics.ES20.DrawElementsType type, [CountAttribute(Computed = "drawcount")] IntPtr indices, int primcount, [CountAttribute(Computed = "drawcount")] ref int basevertex)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] ref int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[] indices, int primcount, [CountAttribute(Computed = "drawcount")] ref int basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] ref int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[,] indices, int primcount, [CountAttribute(Computed = "drawcount")] ref int basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] ref int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[,,] indices, int primcount, [CountAttribute(Computed = "drawcount")] ref int basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] ref int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] ref T3 indices, int primcount, [CountAttribute(Computed = "drawcount")] ref int basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static unsafe void MultiDrawElementsBaseVertex(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int* count, OpenTK.Graphics.ES20.DrawElementsType type, [CountAttribute(Computed = "drawcount")] IntPtr indices, int primcount, [CountAttribute(Computed = "drawcount")] int* basevertex)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static unsafe void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int* count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[] indices, int primcount, [CountAttribute(Computed = "drawcount")] int* basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static unsafe void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int* count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[,] indices, int primcount, [CountAttribute(Computed = "drawcount")] int* basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static unsafe void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int* count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] T3[,,] indices, int primcount, [CountAttribute(Computed = "drawcount")] int* basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            /// <param name="basevertex">
            /// [length: COMPSIZE(drawcount)]
            /// </param>
            [AutoGenerated(Category = "EXT_draw_elements_base_vertex|OES_draw_elements_base_vertex", Version = "", EntryPoint = "glMultiDrawElementsBaseVertexEXT")]
            public static unsafe void MultiDrawElementsBaseVertex<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int* count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "drawcount")] ref T3 indices, int primcount, [CountAttribute(Computed = "drawcount")] int* basevertex)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(390)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiDrawElementsBaseVertexEXT(OpenTK.Graphics.ES20.PrimitiveType mode, [CountAttribute(Computed = "drawcount")] int* count, OpenTK.Graphics.ES20.DrawElementsType type, [CountAttribute(Computed = "drawcount")] IntPtr indices, int primcount, [CountAttribute(Computed = "drawcount")] int* basevertex);
        }
    }
}
