//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES20
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "MemoryObjectWin32" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="handle">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32HandleEXT")]
            public static void ImportMemoryWin32Handle(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [OutAttribute] IntPtr handle)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="handle">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32HandleEXT")]
            public static void ImportMemoryWin32Handle<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] T3[] handle)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="handle">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32HandleEXT")]
            public static void ImportMemoryWin32Handle<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] T3[,] handle)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="handle">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32HandleEXT")]
            public static void ImportMemoryWin32Handle<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] T3[,,] handle)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="handle">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32HandleEXT")]
            public static void ImportMemoryWin32Handle<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] ref T3 handle)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32NameEXT")]
            public static void ImportMemoryWin32Name(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, IntPtr name)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32NameEXT")]
            public static void ImportMemoryWin32Name<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] T3[] name)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32NameEXT")]
            public static void ImportMemoryWin32Name<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] T3[,] name)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32NameEXT")]
            public static void ImportMemoryWin32Name<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] T3[,,] name)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_memory_object_win32]
            /// </summary>
            /// <param name="memory">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="handleType">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_memory_object_win32", Version = "", EntryPoint = "glImportMemoryWin32NameEXT")]
            public static void ImportMemoryWin32Name<T3>(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [InAttribute, OutAttribute] ref T3 name)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(322)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glImportMemoryWin32HandleEXT(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, [OutAttribute] IntPtr handle);

            [Slot(323)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glImportMemoryWin32NameEXT(uint memory, ulong size, OpenTK.Graphics.ES20.ExternalHandleType handleType, IntPtr name);
        }
    }
}
