//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES20
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "MultiviewDrawBuffers" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="location">
            /// [length: n]
            /// </param>
            /// <param name="indices">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glDrawBuffersIndexedEXT")]
            public static void DrawBuffersIndexed(int n, [CountAttribute(Parameter = "n")] ExtMultiviewDrawBuffers[] location, [CountAttribute(Parameter = "n")] int[] indices)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="location">
            /// [length: n]
            /// </param>
            /// <param name="indices">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glDrawBuffersIndexedEXT")]
            public static void DrawBuffersIndexed(int n, [CountAttribute(Parameter = "n")] ref ExtMultiviewDrawBuffers location, [CountAttribute(Parameter = "n")] ref int indices)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="location">
            /// [length: n]
            /// </param>
            /// <param name="indices">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glDrawBuffersIndexedEXT")]
            public static unsafe void DrawBuffersIndexed(int n, [CountAttribute(Parameter = "n")] ExtMultiviewDrawBuffers* location, [CountAttribute(Parameter = "n")] int* indices)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glGetIntegeri_vEXT")]
            public static void GetInteger(OpenTK.Graphics.ES20.GetIndexedPName target, uint index, [OutAttribute] int[] data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glGetIntegeri_vEXT")]
            public static void GetInteger(OpenTK.Graphics.ES20.GetIndexedPName target, uint index, [OutAttribute] out int data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glGetIntegeri_vEXT")]
            public static unsafe void GetInteger(OpenTK.Graphics.ES20.GetIndexedPName target, uint index, [OutAttribute] int* data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_multiview_draw_buffers]
            /// </summary>
            /// <param name="src">
            /// </param>
            /// <param name="index">
            /// </param>
            [AutoGenerated(Category = "EXT_multiview_draw_buffers", Version = "", EntryPoint = "glReadBufferIndexedEXT")]
            public static void ReadBufferIndexed(OpenTK.Graphics.ES20.ReadBufferMode src, int index)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(129)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glDrawBuffersIndexedEXT(int n, [CountAttribute(Parameter = "n")] ExtMultiviewDrawBuffers* location, [CountAttribute(Parameter = "n")] int* indices);

            [Slot(232)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetIntegeri_vEXT(OpenTK.Graphics.ES20.GetIndexedPName target, uint index, [OutAttribute] int* data);

            [Slot(494)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glReadBufferIndexedEXT(OpenTK.Graphics.ES20.ReadBufferMode src, int index);
        }
    }
}
