//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "ByteCoordinates" in the extension "Oes".
        /// </summary>
        public static partial class Oes
        {
            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="s">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord1bOES")]
            public static void MultiTexCoord1(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord1bvOES")]
            public static void MultiTexCoord1(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 1)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord1bvOES")]
            public static unsafe void MultiTexCoord1(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 1)] SByte* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="s">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="t">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord2bOES")]
            public static void MultiTexCoord2(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s, SByte t)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord2bvOES")]
            public static void MultiTexCoord2(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 2)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord2bvOES")]
            public static void MultiTexCoord2(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 2)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord2bvOES")]
            public static unsafe void MultiTexCoord2(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 2)] SByte* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="s">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="t">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="r">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord3bOES")]
            public static void MultiTexCoord3(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s, SByte t, SByte r)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord3bvOES")]
            public static void MultiTexCoord3(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 3)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord3bvOES")]
            public static void MultiTexCoord3(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 3)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord3bvOES")]
            public static unsafe void MultiTexCoord3(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 3)] SByte* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="s">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="t">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="r">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="q">
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord4bOES")]
            public static void MultiTexCoord4(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s, SByte t, SByte r, SByte q)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord4bvOES")]
            public static void MultiTexCoord4(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 4)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord4bvOES")]
            public static void MultiTexCoord4(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 4)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="texture">
            /// Specifies the texture unit whose coordinates should be modified. The number of texture units is implementation dependent, but must be at least two. Symbolic constant must be one of Texture, where i ranges from 0 to MaxTextureCoords - 1, which is an implementation-dependent value.
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// Specify s, t, r, and q texture coordinates for target texture unit. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glMultiTexCoord4bvOES")]
            public static unsafe void MultiTexCoord4(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 4)] SByte* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="s">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord1bOES")]
            public static void TexCoord1(SByte s)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 1]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord1bvOES")]
            public static void TexCoord1([CountAttribute(Count = 1)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="s">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="t">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord2bOES")]
            public static void TexCoord2(SByte s, SByte t)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 2]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord2bvOES")]
            public static void TexCoord2([CountAttribute(Count = 2)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 2]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord2bvOES")]
            public static void TexCoord2([CountAttribute(Count = 2)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="s">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="t">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="r">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord3bOES")]
            public static void TexCoord3(SByte s, SByte t, SByte r)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 3]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord3bvOES")]
            public static void TexCoord3([CountAttribute(Count = 3)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 3]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord3bvOES")]
            public static void TexCoord3([CountAttribute(Count = 3)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="s">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="t">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="r">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="q">
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord4bOES")]
            public static void TexCoord4(SByte s, SByte t, SByte r, SByte q)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 4]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord4bvOES")]
            public static void TexCoord4([CountAttribute(Count = 4)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Set the current texture coordinates
            /// </summary>
            /// <param name="coords">
            /// [length: 4]
            /// Specify s, t, r, and q  texture coordinates. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glTexCoord4bvOES")]
            public static void TexCoord4([CountAttribute(Count = 4)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="x">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="y">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex2bOES")]
            public static void Vertex2(SByte x, SByte y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="coords">
            /// [length: 2]
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex2bvOES")]
            public static void Vertex2([CountAttribute(Count = 2)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="coords">
            /// [length: 2]
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex2bvOES")]
            public static void Vertex2([CountAttribute(Count = 2)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="x">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="y">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="z">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex3bOES")]
            public static void Vertex3(SByte x, SByte y, SByte z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="coords">
            /// [length: 3]
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex3bvOES")]
            public static void Vertex3([CountAttribute(Count = 3)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="coords">
            /// [length: 3]
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex3bvOES")]
            public static void Vertex3([CountAttribute(Count = 3)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="x">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="y">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="z">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            /// <param name="w">
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex4bOES")]
            public static void Vertex4(SByte x, SByte y, SByte z, SByte w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="coords">
            /// [length: 4]
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex4bvOES")]
            public static void Vertex4([CountAttribute(Count = 4)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_byte_coordinates]
            /// Specify a vertex
            /// </summary>
            /// <param name="coords">
            /// [length: 4]
            /// Specify x, y, z, and w coordinates of a vertex. Not all parameters are present in all forms of the command.
            /// </param>
            [AutoGenerated(Category = "OES_byte_coordinates", Version = "", EntryPoint = "glVertex4bvOES")]
            public static void Vertex4([CountAttribute(Count = 4)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1424)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord1bOES(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s);

            [Slot(1425)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord1bvOES(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 1)] SByte* coords);

            [Slot(1446)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord2bOES(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s, SByte t);

            [Slot(1447)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord2bvOES(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 2)] SByte* coords);

            [Slot(1468)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord3bOES(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s, SByte t, SByte r);

            [Slot(1469)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord3bvOES(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 3)] SByte* coords);

            [Slot(1490)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord4bOES(OpenTK.Graphics.OpenGL.TextureUnit texture, SByte s, SByte t, SByte r, SByte q);

            [Slot(1491)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord4bvOES(OpenTK.Graphics.OpenGL.TextureUnit texture, [CountAttribute(Count = 4)] SByte* coords);

            [Slot(2166)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord1bOES(SByte s);

            [Slot(2167)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord1bvOES([CountAttribute(Count = 1)] SByte* coords);

            [Slot(2180)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord2bOES(SByte s, SByte t);

            [Slot(2181)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord2bvOES([CountAttribute(Count = 2)] SByte* coords);

            [Slot(2204)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord3bOES(SByte s, SByte t, SByte r);

            [Slot(2205)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord3bvOES([CountAttribute(Count = 3)] SByte* coords);

            [Slot(2218)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord4bOES(SByte s, SByte t, SByte r, SByte q);

            [Slot(2219)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord4bvOES([CountAttribute(Count = 4)] SByte* coords);

            [Slot(2525)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertex2bOES(SByte x, SByte y);

            [Slot(2526)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertex2bvOES([CountAttribute(Count = 2)] SByte* coords);

            [Slot(2539)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertex3bOES(SByte x, SByte y, SByte z);

            [Slot(2540)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertex3bvOES([CountAttribute(Count = 3)] SByte* coords);

            [Slot(2553)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertex4bOES(SByte x, SByte y, SByte z, SByte w);

            [Slot(2554)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertex4bvOES([CountAttribute(Count = 4)] SByte* coords);
        }
    }
}
