//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "SinglePrecision" in the extension "Oes".
        /// </summary>
        public static partial class Oes
        {
            /// <summary>
            /// [requires: OES_single_precision]
            /// Specify the clear value for the depth buffer
            /// </summary>
            /// <param name="depth">
            /// Specifies the depth value used when the depth buffer is cleared. The initial value is 1.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glClearDepthfOES")]
            public static void ClearDepth(float depth)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Specify a plane against which all geometry is clipped
            /// </summary>
            /// <param name="plane">
            /// Specifies which clipping plane is being positioned. Symbolic names of the form ClipPlanei, where i is an integer between 0 and MaxClipPlanes - 1, are accepted.
            /// </param>
            /// <param name="equation">
            /// [length: 4]
            /// Specifies the address of an array of four double-precision floating-point values. These values are interpreted as a plane equation.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glClipPlanefOES")]
            public static void ClipPlane(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [CountAttribute(Count = 4)] float[] equation)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Specify a plane against which all geometry is clipped
            /// </summary>
            /// <param name="plane">
            /// Specifies which clipping plane is being positioned. Symbolic names of the form ClipPlanei, where i is an integer between 0 and MaxClipPlanes - 1, are accepted.
            /// </param>
            /// <param name="equation">
            /// [length: 4]
            /// Specifies the address of an array of four double-precision floating-point values. These values are interpreted as a plane equation.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glClipPlanefOES")]
            public static void ClipPlane(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [CountAttribute(Count = 4)] ref float equation)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Specify a plane against which all geometry is clipped
            /// </summary>
            /// <param name="plane">
            /// Specifies which clipping plane is being positioned. Symbolic names of the form ClipPlanei, where i is an integer between 0 and MaxClipPlanes - 1, are accepted.
            /// </param>
            /// <param name="equation">
            /// [length: 4]
            /// Specifies the address of an array of four double-precision floating-point values. These values are interpreted as a plane equation.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glClipPlanefOES")]
            public static unsafe void ClipPlane(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [CountAttribute(Count = 4)] float* equation)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Specify mapping of depth values from normalized device coordinates to window coordinates
            /// </summary>
            /// <param name="n">
            /// Specifies the mapping of the near clipping plane to window coordinates. The initial value is 0.
            /// </param>
            /// <param name="f">
            /// Specifies the mapping of the far clipping plane to window coordinates. The initial value is 1.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glDepthRangefOES")]
            public static void DepthRange(float n, float f)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Multiply the current matrix by a perspective matrix
            /// </summary>
            /// <param name="l">
            /// Specify the coordinates for the left and right vertical clipping planes.
            /// </param>
            /// <param name="r">
            /// Specify the coordinates for the left and right vertical clipping planes.
            /// </param>
            /// <param name="b">
            /// Specify the coordinates for the bottom and top horizontal clipping planes.
            /// </param>
            /// <param name="t">
            /// Specify the coordinates for the bottom and top horizontal clipping planes.
            /// </param>
            /// <param name="n">
            /// Specify the distances to the near and far depth clipping planes. Both distances must be positive.
            /// </param>
            /// <param name="f">
            /// Specify the distances to the near and far depth clipping planes. Both distances must be positive.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glFrustumfOES")]
            public static void Frustum(float l, float r, float b, float t, float n, float f)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Return the coefficients of the specified clipping plane
            /// </summary>
            /// <param name="plane">
            /// Specifies a clipping plane. The number of clipping planes depends on the implementation, but at least six clipping planes are supported. They are identified by symbolic names of the form ClipPlane  where i ranges from 0 to the value of MaxClipPlanes - 1.
            /// </param>
            /// <param name="equation">
            /// [length: 4]
            /// Returns four double-precision values that are the coefficients of the plane equation of plane in eye coordinates. The initial value is (0, 0, 0, 0).
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glGetClipPlanefOES")]
            public static void GetClipPlane(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [OutAttribute, CountAttribute(Count = 4)] float[] equation)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Return the coefficients of the specified clipping plane
            /// </summary>
            /// <param name="plane">
            /// Specifies a clipping plane. The number of clipping planes depends on the implementation, but at least six clipping planes are supported. They are identified by symbolic names of the form ClipPlane  where i ranges from 0 to the value of MaxClipPlanes - 1.
            /// </param>
            /// <param name="equation">
            /// [length: 4]
            /// Returns four double-precision values that are the coefficients of the plane equation of plane in eye coordinates. The initial value is (0, 0, 0, 0).
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glGetClipPlanefOES")]
            public static void GetClipPlane(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [OutAttribute, CountAttribute(Count = 4)] out float equation)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Return the coefficients of the specified clipping plane
            /// </summary>
            /// <param name="plane">
            /// Specifies a clipping plane. The number of clipping planes depends on the implementation, but at least six clipping planes are supported. They are identified by symbolic names of the form ClipPlane  where i ranges from 0 to the value of MaxClipPlanes - 1.
            /// </param>
            /// <param name="equation">
            /// [length: 4]
            /// Returns four double-precision values that are the coefficients of the plane equation of plane in eye coordinates. The initial value is (0, 0, 0, 0).
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glGetClipPlanefOES")]
            public static unsafe void GetClipPlane(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [OutAttribute, CountAttribute(Count = 4)] float* equation)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_single_precision]
            /// Multiply the current matrix with an orthographic matrix
            /// </summary>
            /// <param name="l">
            /// Specify the coordinates for the left and right vertical clipping planes.
            /// </param>
            /// <param name="r">
            /// Specify the coordinates for the left and right vertical clipping planes.
            /// </param>
            /// <param name="b">
            /// Specify the coordinates for the bottom and top horizontal clipping planes.
            /// </param>
            /// <param name="t">
            /// Specify the coordinates for the bottom and top horizontal clipping planes.
            /// </param>
            /// <param name="n">
            /// Specify the distances to the nearer and farther depth clipping planes. These values are negative if the plane is to be behind the viewer.
            /// </param>
            /// <param name="f">
            /// Specify the distances to the nearer and farther depth clipping planes. These values are negative if the plane is to be behind the viewer.
            /// </param>
            [AutoGenerated(Category = "OES_single_precision", Version = "", EntryPoint = "glOrthofOES")]
            public static void Ortho(float l, float r, float b, float t, float n, float f)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(170)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glClearDepthfOES(float depth);

            [Slot(191)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glClipPlanefOES(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [CountAttribute(Count = 4)] float* equation);

            [Slot(452)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDepthRangefOES(float n, float f);

            [Slot(656)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glFrustumfOES(float l, float r, float b, float t, float n, float f);

            [Slot(726)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetClipPlanefOES(OpenTK.Graphics.OpenGL.ClipPlaneName plane, [OutAttribute, CountAttribute(Count = 4)] float* equation);

            [Slot(1641)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glOrthofOES(float l, float r, float b, float t, float n, float f);
        }
    }
}
