//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES20
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "InstancedArrays" in the extension "Angle".
        /// </summary>
        public static partial class Angle
        {
            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="primcount">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glDrawArraysInstancedANGLE")]
            public static void DrawArraysInstanced(OpenTK.Graphics.ES20.PrimitiveType mode, int first, int count, int primcount)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(count,type)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glDrawElementsInstancedANGLE")]
            public static void DrawElementsInstanced(OpenTK.Graphics.ES20.PrimitiveType mode, int count, OpenTK.Graphics.ES20.DrawElementsType type, [CountAttribute(Computed = "count,type")] IntPtr indices, int primcount)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(count,type)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glDrawElementsInstancedANGLE")]
            public static void DrawElementsInstanced<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "count,type")] T3[] indices, int primcount)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(count,type)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glDrawElementsInstancedANGLE")]
            public static void DrawElementsInstanced<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "count,type")] T3[,] indices, int primcount)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(count,type)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glDrawElementsInstancedANGLE")]
            public static void DrawElementsInstanced<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "count,type")] T3[,,] indices, int primcount)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="indices">
            /// [length: COMPSIZE(count,type)]
            /// </param>
            /// <param name="primcount">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glDrawElementsInstancedANGLE")]
            public static void DrawElementsInstanced<T3>(OpenTK.Graphics.ES20.PrimitiveType mode, int count, OpenTK.Graphics.ES20.DrawElementsType type, [InAttribute, OutAttribute, CountAttribute(Computed = "count,type")] ref T3 indices, int primcount)
                where T3 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_instanced_arrays]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="divisor">
            /// </param>
            [AutoGenerated(Category = "ANGLE_instanced_arrays", Version = "", EntryPoint = "glVertexAttribDivisorANGLE")]
            public static void VertexAttribDivisor(uint index, uint divisor)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(124)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDrawArraysInstancedANGLE(OpenTK.Graphics.ES20.PrimitiveType mode, int first, int count, int primcount);

            [Slot(134)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDrawElementsInstancedANGLE(OpenTK.Graphics.ES20.PrimitiveType mode, int count, OpenTK.Graphics.ES20.DrawElementsType type, [CountAttribute(Computed = "count,type")] IntPtr indices, int primcount);

            [Slot(644)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribDivisorANGLE(uint index, uint divisor);
        }
    }
}
