//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES20
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "TranslatedShaderSource" in the extension "Angle".
        /// </summary>
        public static partial class Angle
        {
            /// <summary>
            /// [requires: ANGLE_translated_shader_source]
            /// </summary>
            /// <param name="shader">
            /// </param>
            /// <param name="bufsize">
            /// </param>
            /// <param name="length">
            /// [length: 1]
            /// </param>
            /// <param name="source">
            /// [length: bufsize]
            /// </param>
            [AutoGenerated(Category = "ANGLE_translated_shader_source", Version = "", EntryPoint = "glGetTranslatedShaderSourceANGLE")]
            public static void GetTranslatedShaderSource(uint shader, int bufsize, [OutAttribute, CountAttribute(Count = 1)] out int length, [OutAttribute, CountAttribute(Parameter = "bufsize")] out String source)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ANGLE_translated_shader_source]
            /// </summary>
            /// <param name="shader">
            /// </param>
            /// <param name="bufsize">
            /// </param>
            /// <param name="length">
            /// [length: 1]
            /// </param>
            /// <param name="source">
            /// [length: bufsize]
            /// </param>
            [AutoGenerated(Category = "ANGLE_translated_shader_source", Version = "", EntryPoint = "glGetTranslatedShaderSourceANGLE")]
            public static unsafe void GetTranslatedShaderSource(uint shader, int bufsize, [OutAttribute, CountAttribute(Count = 1)] int* length, [OutAttribute, CountAttribute(Parameter = "bufsize")] out String source)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(309)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetTranslatedShaderSourceANGLE(uint shader, int bufsize, [OutAttribute, CountAttribute(Count = 1)] int* length, [OutAttribute, CountAttribute(Parameter = "bufsize")] IntPtr source);
        }
    }
}
