//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "Texture4D" in the extension "Sgis".
        /// </summary>
        public static partial class Sgis
        {
            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="internalformat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="border">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexImage4DSGIS")]
            public static void TexImage4D(OpenTK.Graphics.OpenGL.TextureTarget target, int level, OpenTK.Graphics.OpenGL.InternalFormat internalformat, int width, int height, int depth, int size4d, int border, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [CountAttribute(Computed = "format,type,width,height,depth,size4d")] IntPtr pixels)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="internalformat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="border">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexImage4DSGIS")]
            public static void TexImage4D<T10>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, OpenTK.Graphics.OpenGL.InternalFormat internalformat, int width, int height, int depth, int size4d, int border, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] T10[] pixels)
                where T10 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="internalformat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="border">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexImage4DSGIS")]
            public static void TexImage4D<T10>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, OpenTK.Graphics.OpenGL.InternalFormat internalformat, int width, int height, int depth, int size4d, int border, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] T10[,] pixels)
                where T10 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="internalformat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="border">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexImage4DSGIS")]
            public static void TexImage4D<T10>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, OpenTK.Graphics.OpenGL.InternalFormat internalformat, int width, int height, int depth, int size4d, int border, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] T10[,,] pixels)
                where T10 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="internalformat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="border">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexImage4DSGIS")]
            public static void TexImage4D<T10>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, OpenTK.Graphics.OpenGL.InternalFormat internalformat, int width, int height, int depth, int size4d, int border, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] ref T10 pixels)
                where T10 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="xoffset">
            /// </param>
            /// <param name="yoffset">
            /// </param>
            /// <param name="zoffset">
            /// </param>
            /// <param name="woffset">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexSubImage4DSGIS")]
            public static void TexSubImage4D(OpenTK.Graphics.OpenGL.TextureTarget target, int level, int xoffset, int yoffset, int zoffset, int woffset, int width, int height, int depth, int size4d, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [CountAttribute(Computed = "format,type,width,height,depth,size4d")] IntPtr pixels)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="xoffset">
            /// </param>
            /// <param name="yoffset">
            /// </param>
            /// <param name="zoffset">
            /// </param>
            /// <param name="woffset">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexSubImage4DSGIS")]
            public static void TexSubImage4D<T12>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, int xoffset, int yoffset, int zoffset, int woffset, int width, int height, int depth, int size4d, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] T12[] pixels)
                where T12 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="xoffset">
            /// </param>
            /// <param name="yoffset">
            /// </param>
            /// <param name="zoffset">
            /// </param>
            /// <param name="woffset">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexSubImage4DSGIS")]
            public static void TexSubImage4D<T12>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, int xoffset, int yoffset, int zoffset, int woffset, int width, int height, int depth, int size4d, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] T12[,] pixels)
                where T12 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="xoffset">
            /// </param>
            /// <param name="yoffset">
            /// </param>
            /// <param name="zoffset">
            /// </param>
            /// <param name="woffset">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexSubImage4DSGIS")]
            public static void TexSubImage4D<T12>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, int xoffset, int yoffset, int zoffset, int woffset, int width, int height, int depth, int size4d, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] T12[,,] pixels)
                where T12 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture4D]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="xoffset">
            /// </param>
            /// <param name="yoffset">
            /// </param>
            /// <param name="zoffset">
            /// </param>
            /// <param name="woffset">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="size4d">
            /// </param>
            /// <param name="format">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="pixels">
            /// [length: COMPSIZE(format,type,width,height,depth,size4d)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture4D", Version = "", EntryPoint = "glTexSubImage4DSGIS")]
            public static void TexSubImage4D<T12>(OpenTK.Graphics.OpenGL.TextureTarget target, int level, int xoffset, int yoffset, int zoffset, int woffset, int width, int height, int depth, int size4d, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [InAttribute, OutAttribute, CountAttribute(Computed = "format,type,width,height,depth,size4d")] ref T12 pixels)
                where T12 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(2272)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexImage4DSGIS(OpenTK.Graphics.OpenGL.TextureTarget target, int level, OpenTK.Graphics.OpenGL.InternalFormat internalformat, int width, int height, int depth, int size4d, int border, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [CountAttribute(Computed = "format,type,width,height,depth,size4d")] IntPtr pixels);

            [Slot(2302)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexSubImage4DSGIS(OpenTK.Graphics.OpenGL.TextureTarget target, int level, int xoffset, int yoffset, int zoffset, int woffset, int width, int height, int depth, int size4d, OpenTK.Graphics.OpenGL.PixelFormat format, OpenTK.Graphics.OpenGL.PixelType type, [CountAttribute(Computed = "format,type,width,height,depth,size4d")] IntPtr pixels);
        }
    }
}
