//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "TextureFilter4" in the extension "Sgis".
        /// </summary>
        public static partial class Sgis
        {
            /// <summary>
            /// [requires: SGIS_texture_filter4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="filter">
            /// </param>
            /// <param name="weights">
            /// [length: COMPSIZE(target,filter)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture_filter4", Version = "", EntryPoint = "glGetTexFilterFuncSGIS")]
            public static void GetTexFilterFunc(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, [OutAttribute, CountAttribute(Computed = "target,filter")] float[] weights)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture_filter4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="filter">
            /// </param>
            /// <param name="weights">
            /// [length: COMPSIZE(target,filter)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture_filter4", Version = "", EntryPoint = "glGetTexFilterFuncSGIS")]
            public static void GetTexFilterFunc(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, [OutAttribute, CountAttribute(Computed = "target,filter")] out float weights)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture_filter4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="filter">
            /// </param>
            /// <param name="weights">
            /// [length: COMPSIZE(target,filter)]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture_filter4", Version = "", EntryPoint = "glGetTexFilterFuncSGIS")]
            public static unsafe void GetTexFilterFunc(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, [OutAttribute, CountAttribute(Computed = "target,filter")] float* weights)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture_filter4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="filter">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="weights">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture_filter4", Version = "", EntryPoint = "glTexFilterFuncSGIS")]
            public static void TexFilterFunc(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, int n, [CountAttribute(Parameter = "n")] float[] weights)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture_filter4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="filter">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="weights">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture_filter4", Version = "", EntryPoint = "glTexFilterFuncSGIS")]
            public static void TexFilterFunc(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, int n, [CountAttribute(Parameter = "n")] ref float weights)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: SGIS_texture_filter4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="filter">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="weights">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "SGIS_texture_filter4", Version = "", EntryPoint = "glTexFilterFuncSGIS")]
            public static unsafe void TexFilterFunc(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, int n, [CountAttribute(Parameter = "n")] float* weights)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1049)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetTexFilterFuncSGIS(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, [OutAttribute, CountAttribute(Computed = "target,filter")] float* weights);

            [Slot(2255)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexFilterFuncSGIS(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.SgisTextureFilter4 filter, int n, [CountAttribute(Parameter = "n")] float* weights);
        }
    }
}
