//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "ConditionalRender" in the extension "Nvx".
        /// </summary>
        public static partial class Nvx
        {
            /// <summary>
            /// [requires: NVX_conditional_render]
            /// Start conditional rendering
            /// </summary>
            /// <param name="id">
            /// Specifies the name of an occlusion query object whose results are used to determine if the rendering commands are discarded.
            /// </param>
            [AutoGenerated(Category = "NVX_conditional_render", Version = "", EntryPoint = "glBeginConditionalRenderNVX")]
            public static void BeginConditionalRender(uint id)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NVX_conditional_render]
            /// </summary>
            [AutoGenerated(Category = "NVX_conditional_render", Version = "", EntryPoint = "glEndConditionalRenderNVX")]
            public static void EndConditionalRender()
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(30)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBeginConditionalRenderNVX(uint id);

            [Slot(538)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glEndConditionalRenderNVX();
        }
    }
}
