//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "SparseTexture" in the extension "Amd".
        /// </summary>
        public static partial class Amd
        {
            /// <summary>
            /// [requires: AMD_sparse_texture]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="layers">
            /// </param>
            /// <param name="flags">
            /// </param>
            [AutoGenerated(Category = "AMD_sparse_texture", Version = "", EntryPoint = "glTexStorageSparseAMD")]
            public static void TexStorageSparse(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.InternalFormat internalFormat, int width, int height, int depth, int layers, OpenTK.Graphics.OpenGL.TextureStorageMaskAmd flags)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: AMD_sparse_texture]
            /// </summary>
            /// <param name="texture">
            /// </param>
            /// <param name="target">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="layers">
            /// </param>
            /// <param name="flags">
            /// </param>
            [AutoGenerated(Category = "AMD_sparse_texture", Version = "", EntryPoint = "glTextureStorageSparseAMD")]
            public static void TextureStorageSparse(uint texture, OpenTK.Graphics.OpenGL.AmdSparseTexture target, OpenTK.Graphics.OpenGL.InternalFormat internalFormat, int width, int height, int depth, int layers, OpenTK.Graphics.OpenGL.TextureStorageMaskAmd flags)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(2295)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexStorageSparseAMD(OpenTK.Graphics.OpenGL.TextureTarget target, OpenTK.Graphics.OpenGL.InternalFormat internalFormat, int width, int height, int depth, int layers, OpenTK.Graphics.OpenGL.TextureStorageMaskAmd flags);

            [Slot(2350)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTextureStorageSparseAMD(uint texture, OpenTK.Graphics.OpenGL.AmdSparseTexture target, OpenTK.Graphics.OpenGL.InternalFormat internalFormat, int width, int height, int depth, int layers, OpenTK.Graphics.OpenGL.TextureStorageMaskAmd flags);
        }
    }
}
