//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "Fence" in the extension "Apple".
        /// </summary>
        public static partial class Apple
        {
            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glDeleteFencesAPPLE")]
            public static void DeleteFence([CountAttribute(Parameter = "n")] uint fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glDeleteFencesAPPLE")]
            public static void DeleteFences(int n, [CountAttribute(Parameter = "n")] uint[] fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glDeleteFencesAPPLE")]
            public static void DeleteFences(int n, [CountAttribute(Parameter = "n")] ref uint fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glDeleteFencesAPPLE")]
            public static unsafe void DeleteFences(int n, [CountAttribute(Parameter = "n")] uint* fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="fence">
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glFinishFenceAPPLE")]
            public static void FinishFence(uint fence)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="@object">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glFinishObjectAPPLE")]
            public static void FinishObject(OpenTK.Graphics.OpenGL.AppleFence @object, int name)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glGenFencesAPPLE")]
            public static uint GenFence()
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glGenFencesAPPLE")]
            public static void GenFences(int n, [OutAttribute, CountAttribute(Parameter = "n")] uint[] fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glGenFencesAPPLE")]
            public static void GenFences(int n, [OutAttribute, CountAttribute(Parameter = "n")] out uint fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="n">
            /// </param>
            /// <param name="fences">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glGenFencesAPPLE")]
            public static unsafe void GenFences(int n, [OutAttribute, CountAttribute(Parameter = "n")] uint* fences)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="fence">
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glIsFenceAPPLE")]
            public static bool IsFence(uint fence)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="fence">
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glSetFenceAPPLE")]
            public static void SetFence(uint fence)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="fence">
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glTestFenceAPPLE")]
            public static bool TestFence(uint fence)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_fence]
            /// </summary>
            /// <param name="@object">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "APPLE_fence", Version = "", EntryPoint = "glTestObjectAPPLE")]
            public static bool TestObject(OpenTK.Graphics.OpenGL.AppleFence @object, uint name)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(408)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glDeleteFencesAPPLE(int n, [CountAttribute(Parameter = "n")] uint* fences);

            [Slot(578)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glFinishFenceAPPLE(uint fence);

            [Slot(580)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glFinishObjectAPPLE(OpenTK.Graphics.OpenGL.AppleFence @object, int name);

            [Slot(666)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGenFencesAPPLE(int n, [OutAttribute, CountAttribute(Parameter = "n")] uint* fences);

            [Slot(1223)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern byte glIsFenceAPPLE(uint fence);

            [Slot(2093)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glSetFenceAPPLE(uint fence);

            [Slot(2157)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern byte glTestFenceAPPLE(uint fence);

            [Slot(2159)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern byte glTestObjectAPPLE(OpenTK.Graphics.OpenGL.AppleFence @object, uint name);
        }
    }
}
