//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "ObjectPurgeable" in the extension "Apple".
        /// </summary>
        public static partial class Apple
        {
            /// <summary>
            /// [requires: APPLE_object_purgeable]
            /// </summary>
            /// <param name="objectType">
            /// </param>
            /// <param name="name">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "APPLE_object_purgeable", Version = "", EntryPoint = "glGetObjectParameterivAPPLE")]
            public static void GetObjectParameter(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_object_purgeable]
            /// </summary>
            /// <param name="objectType">
            /// </param>
            /// <param name="name">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "APPLE_object_purgeable", Version = "", EntryPoint = "glGetObjectParameterivAPPLE")]
            public static void GetObjectParameter(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable pname, [OutAttribute, CountAttribute(Computed = "pname")] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_object_purgeable]
            /// </summary>
            /// <param name="objectType">
            /// </param>
            /// <param name="name">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "APPLE_object_purgeable", Version = "", EntryPoint = "glGetObjectParameterivAPPLE")]
            public static unsafe void GetObjectParameter(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_object_purgeable]
            /// </summary>
            /// <param name="objectType">
            /// </param>
            /// <param name="name">
            /// </param>
            /// <param name="option">
            /// </param>
            [AutoGenerated(Category = "APPLE_object_purgeable", Version = "", EntryPoint = "glObjectPurgeableAPPLE")]
            public static OpenTK.Graphics.OpenGL.AppleObjectPurgeable ObjectPurgeable(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable option)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_object_purgeable]
            /// </summary>
            /// <param name="objectType">
            /// </param>
            /// <param name="name">
            /// </param>
            /// <param name="option">
            /// </param>
            [AutoGenerated(Category = "APPLE_object_purgeable", Version = "", EntryPoint = "glObjectUnpurgeableAPPLE")]
            public static OpenTK.Graphics.OpenGL.AppleObjectPurgeable ObjectUnpurgeable(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable option)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(933)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetObjectParameterivAPPLE(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params);

            [Slot(1638)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern OpenTK.Graphics.OpenGL.AppleObjectPurgeable glObjectPurgeableAPPLE(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable option);

            [Slot(1639)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern OpenTK.Graphics.OpenGL.AppleObjectPurgeable glObjectUnpurgeableAPPLE(OpenTK.Graphics.OpenGL.AppleObjectPurgeable objectType, uint name, OpenTK.Graphics.OpenGL.AppleObjectPurgeable option);
        }
    }
}
