//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "TextureRange" in the extension "Apple".
        /// </summary>
        public static partial class Apple
        {
            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glGetTexParameterPointervAPPLE")]
            public static void GetTexParameterPointer(OpenTK.Graphics.OpenGL.AppleTextureRange target, OpenTK.Graphics.OpenGL.AppleTextureRange pname, [OutAttribute, CountAttribute(Count = 1)] IntPtr @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glGetTexParameterPointervAPPLE")]
            public static void GetTexParameterPointer<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, OpenTK.Graphics.OpenGL.AppleTextureRange pname, [InAttribute, OutAttribute, CountAttribute(Count = 1)] T2[] @params)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glGetTexParameterPointervAPPLE")]
            public static void GetTexParameterPointer<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, OpenTK.Graphics.OpenGL.AppleTextureRange pname, [InAttribute, OutAttribute, CountAttribute(Count = 1)] T2[,] @params)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glGetTexParameterPointervAPPLE")]
            public static void GetTexParameterPointer<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, OpenTK.Graphics.OpenGL.AppleTextureRange pname, [InAttribute, OutAttribute, CountAttribute(Count = 1)] T2[,,] @params)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glGetTexParameterPointervAPPLE")]
            public static void GetTexParameterPointer<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, OpenTK.Graphics.OpenGL.AppleTextureRange pname, [InAttribute, OutAttribute, CountAttribute(Count = 1)] ref T2 @params)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="length">
            /// </param>
            /// <param name="pointer">
            /// [length: length]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glTextureRangeAPPLE")]
            public static void TextureRange(OpenTK.Graphics.OpenGL.AppleTextureRange target, int length, [CountAttribute(Parameter = "length")] IntPtr pointer)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="length">
            /// </param>
            /// <param name="pointer">
            /// [length: length]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glTextureRangeAPPLE")]
            public static void TextureRange<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, int length, [InAttribute, OutAttribute, CountAttribute(Parameter = "length")] T2[] pointer)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="length">
            /// </param>
            /// <param name="pointer">
            /// [length: length]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glTextureRangeAPPLE")]
            public static void TextureRange<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, int length, [InAttribute, OutAttribute, CountAttribute(Parameter = "length")] T2[,] pointer)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="length">
            /// </param>
            /// <param name="pointer">
            /// [length: length]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glTextureRangeAPPLE")]
            public static void TextureRange<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, int length, [InAttribute, OutAttribute, CountAttribute(Parameter = "length")] T2[,,] pointer)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: APPLE_texture_range]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="length">
            /// </param>
            /// <param name="pointer">
            /// [length: length]
            /// </param>
            [AutoGenerated(Category = "APPLE_texture_range", Version = "", EntryPoint = "glTextureRangeAPPLE")]
            public static void TextureRange<T2>(OpenTK.Graphics.OpenGL.AppleTextureRange target, int length, [InAttribute, OutAttribute, CountAttribute(Parameter = "length")] ref T2 pointer)
                where T2 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1064)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glGetTexParameterPointervAPPLE(OpenTK.Graphics.OpenGL.AppleTextureRange target, OpenTK.Graphics.OpenGL.AppleTextureRange pname, [OutAttribute, CountAttribute(Count = 1)] IntPtr @params);

            [Slot(2333)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTextureRangeAPPLE(OpenTK.Graphics.OpenGL.AppleTextureRange target, int length, [CountAttribute(Parameter = "length")] IntPtr pointer);
        }
    }
}
