//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL4
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "DirectStateAccess|NVPathRendering" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="left">
            /// </param>
            /// <param name="right">
            /// </param>
            /// <param name="bottom">
            /// </param>
            /// <param name="top">
            /// </param>
            /// <param name="zNear">
            /// </param>
            /// <param name="zFar">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixFrustumEXT")]
            public static void MatrixFrustum(OpenTK.Graphics.OpenGL4.MatrixMode mode, double left, double right, double bottom, double top, double zNear, double zFar)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadIdentityEXT")]
            public static void MatrixLoadIdentity(OpenTK.Graphics.OpenGL4.MatrixMode mode)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadTransposedEXT")]
            public static void MatrixLoadTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadTransposedEXT")]
            public static void MatrixLoadTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref double m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadTransposedEXT")]
            public static unsafe void MatrixLoadTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadTransposefEXT")]
            public static void MatrixLoadTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadTransposefEXT")]
            public static void MatrixLoadTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref float m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadTransposefEXT")]
            public static unsafe void MatrixLoadTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoaddEXT")]
            public static void MatrixLoad(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoaddEXT")]
            public static void MatrixLoad(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref double m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoaddEXT")]
            public static unsafe void MatrixLoad(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadfEXT")]
            public static void MatrixLoad(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadfEXT")]
            public static void MatrixLoad(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref float m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixLoadfEXT")]
            public static unsafe void MatrixLoad(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultTransposedEXT")]
            public static void MatrixMultTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultTransposedEXT")]
            public static void MatrixMultTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref double m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultTransposedEXT")]
            public static unsafe void MatrixMultTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultTransposefEXT")]
            public static void MatrixMultTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultTransposefEXT")]
            public static void MatrixMultTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref float m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultTransposefEXT")]
            public static unsafe void MatrixMultTranspose(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultdEXT")]
            public static void MatrixMult(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultdEXT")]
            public static void MatrixMult(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref double m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultdEXT")]
            public static unsafe void MatrixMult(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultfEXT")]
            public static void MatrixMult(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float[] m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultfEXT")]
            public static void MatrixMult(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] ref float m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="m">
            /// [length: 16]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixMultfEXT")]
            public static unsafe void MatrixMult(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="left">
            /// </param>
            /// <param name="right">
            /// </param>
            /// <param name="bottom">
            /// </param>
            /// <param name="top">
            /// </param>
            /// <param name="zNear">
            /// </param>
            /// <param name="zFar">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixOrthoEXT")]
            public static void MatrixOrtho(OpenTK.Graphics.OpenGL4.MatrixMode mode, double left, double right, double bottom, double top, double zNear, double zFar)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixPopEXT")]
            public static void MatrixPop(OpenTK.Graphics.OpenGL4.MatrixMode mode)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixPushEXT")]
            public static void MatrixPush(OpenTK.Graphics.OpenGL4.MatrixMode mode)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="angle">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixRotatedEXT")]
            public static void MatrixRotate(OpenTK.Graphics.OpenGL4.MatrixMode mode, double angle, double x, double y, double z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="angle">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixRotatefEXT")]
            public static void MatrixRotate(OpenTK.Graphics.OpenGL4.MatrixMode mode, float angle, float x, float y, float z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixScaledEXT")]
            public static void MatrixScale(OpenTK.Graphics.OpenGL4.MatrixMode mode, double x, double y, double z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixScalefEXT")]
            public static void MatrixScale(OpenTK.Graphics.OpenGL4.MatrixMode mode, float x, float y, float z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixTranslatedEXT")]
            public static void MatrixTranslate(OpenTK.Graphics.OpenGL4.MatrixMode mode, double x, double y, double z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|NV_path_rendering]
            /// </summary>
            /// <param name="mode">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|NV_path_rendering", Version = "", EntryPoint = "glMatrixTranslatefEXT")]
            public static void MatrixTranslate(OpenTK.Graphics.OpenGL4.MatrixMode mode, float x, float y, float z)
            {
                throw new BindingsNotRewrittenException();
            }

            #pragma warning disable SA1300 // Element should begin with an upper-case letter

            [Slot(664)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixFrustumEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, double left, double right, double bottom, double top, double zNear, double zFar);

            [Slot(669)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixLoadIdentityEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode);

            [Slot(671)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixLoadTransposedEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m);

            [Slot(672)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixLoadTransposefEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m);

            [Slot(667)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixLoaddEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m);

            [Slot(668)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixLoadfEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m);

            [Slot(678)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixMultTransposedEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m);

            [Slot(679)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixMultTransposefEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m);

            [Slot(675)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixMultdEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] double* m);

            [Slot(676)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMatrixMultfEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, [CountAttribute(Count = 16)] float* m);

            [Slot(680)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixOrthoEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, double left, double right, double bottom, double top, double zNear, double zFar);

            [Slot(681)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixPopEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode);

            [Slot(682)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixPushEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode);

            [Slot(683)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixRotatedEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, double angle, double x, double y, double z);

            [Slot(684)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixRotatefEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, float angle, float x, float y, float z);

            [Slot(685)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixScaledEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, double x, double y, double z);

            [Slot(686)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixScalefEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, float x, float y, float z);

            [Slot(687)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixTranslatedEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, double x, double y, double z);

            [Slot(688)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMatrixTranslatefEXT(OpenTK.Graphics.OpenGL4.MatrixMode mode, float x, float y, float z);
        }
    }
}
