//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES30
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "ViewportArray" in the extension "Oes".
        /// </summary>
        public static partial class Oes
        {
            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glDepthRangeArrayfvOES")]
            public static void DepthRangeArray(uint first, int count, float[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glDepthRangeArrayfvOES")]
            public static void DepthRangeArray(uint first, int count, ref float v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glDepthRangeArrayfvOES")]
            public static unsafe void DepthRangeArray(uint first, int count, float* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="f">
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glDepthRangeIndexedfOES")]
            public static void DepthRangeIndexed(uint index, float n, float f)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glGetFloati_vOES")]
            public static void GetFloat(OpenTK.Graphics.ES30.TypeEnum target, uint index, [OutAttribute, CountAttribute(Computed = "target")] float[] data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glGetFloati_vOES")]
            public static void GetFloat(OpenTK.Graphics.ES30.TypeEnum target, uint index, [OutAttribute, CountAttribute(Computed = "target")] out float data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glGetFloati_vOES")]
            public static unsafe void GetFloat(OpenTK.Graphics.ES30.TypeEnum target, uint index, [OutAttribute, CountAttribute(Computed = "target")] float* data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// [length: COMPSIZE(count)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorArrayvOES")]
            public static void ScissorArray(uint first, int count, [CountAttribute(Computed = "count")] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// [length: COMPSIZE(count)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorArrayvOES")]
            public static void ScissorArray(uint first, int count, [CountAttribute(Computed = "count")] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// [length: COMPSIZE(count)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorArrayvOES")]
            public static unsafe void ScissorArray(uint first, int count, [CountAttribute(Computed = "count")] int* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="left">
            /// </param>
            /// <param name="bottom">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorIndexedOES")]
            public static void ScissorIndexed(uint index, int left, int bottom, int width, int height)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorIndexedvOES")]
            public static void ScissorIndexed(uint index, [CountAttribute(Count = 4)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorIndexedvOES")]
            public static void ScissorIndexed(uint index, [CountAttribute(Count = 4)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glScissorIndexedvOES")]
            public static unsafe void ScissorIndexed(uint index, [CountAttribute(Count = 4)] int* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// [length: COMPSIZE(count)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportArrayvOES")]
            public static void ViewportArray(uint first, int count, [CountAttribute(Computed = "count")] float[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// [length: COMPSIZE(count)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportArrayvOES")]
            public static void ViewportArray(uint first, int count, [CountAttribute(Computed = "count")] ref float v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="first">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="v">
            /// [length: COMPSIZE(count)]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportArrayvOES")]
            public static unsafe void ViewportArray(uint first, int count, [CountAttribute(Computed = "count")] float* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="w">
            /// </param>
            /// <param name="h">
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportIndexedfOES")]
            public static void ViewportIndexed(uint index, float x, float y, float w, float h)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportIndexedfvOES")]
            public static void ViewportIndexed(uint index, [CountAttribute(Count = 4)] float[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportIndexedfvOES")]
            public static void ViewportIndexed(uint index, [CountAttribute(Count = 4)] ref float v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: OES_viewport_array]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "OES_viewport_array", Version = "", EntryPoint = "glViewportIndexedfvOES")]
            public static unsafe void ViewportIndexed(uint index, [CountAttribute(Count = 4)] float* v)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(133)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glDepthRangeArrayfvOES(uint first, int count, float* v);

            [Slot(136)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDepthRangeIndexedfOES(uint index, float n, float f);

            [Slot(262)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetFloati_vOES(OpenTK.Graphics.ES30.TypeEnum target, uint index, [OutAttribute, CountAttribute(Computed = "target")] float* data);

            [Slot(593)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glScissorArrayvOES(uint first, int count, [CountAttribute(Computed = "count")] int* v);

            [Slot(595)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glScissorIndexedOES(uint index, int left, int bottom, int width, int height);

            [Slot(597)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glScissorIndexedvOES(uint index, [CountAttribute(Count = 4)] int* v);

            [Slot(753)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glViewportArrayvOES(uint first, int count, [CountAttribute(Computed = "count")] float* v);

            [Slot(755)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glViewportIndexedfOES(uint index, float x, float y, float w, float h);

            [Slot(757)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glViewportIndexedfvOES(uint index, [CountAttribute(Count = 4)] float* v);
        }
    }
}
