//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "EnvmapBumpmap" in the extension "Ati".
        /// </summary>
        public static partial class Ati
        {
            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterfvATI")]
            public static float GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterfvATI")]
            public static void GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] float[] param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterfvATI")]
            public static void GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] out float param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterfvATI")]
            public static unsafe void GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] float* param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterivATI")]
            public static void GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterivATI")]
            public static void GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] out int param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glGetTexBumpParameterivATI")]
            public static unsafe void GetTexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] int* param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glTexBumpParameterfvATI")]
            public static void TexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] float[] param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glTexBumpParameterfvATI")]
            public static void TexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] ref float param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glTexBumpParameterfvATI")]
            public static unsafe void TexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] float* param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glTexBumpParameterivATI")]
            public static void TexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] int[] param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glTexBumpParameterivATI")]
            public static void TexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] ref int param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_envmap_bumpmap]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_envmap_bumpmap", Version = "", EntryPoint = "glTexBumpParameterivATI")]
            public static unsafe void TexBumpParameter(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] int* param)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1044)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetTexBumpParameterfvATI(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] float* param);

            [Slot(1045)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetTexBumpParameterivATI(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [OutAttribute, CountAttribute(Computed = "pname")] int* param);

            [Slot(2164)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexBumpParameterfvATI(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] float* param);

            [Slot(2165)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexBumpParameterivATI(OpenTK.Graphics.OpenGL.AtiEnvmapBumpmap pname, [CountAttribute(Computed = "pname")] int* param);
        }
    }
}
