//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "VertexAttribArrayObject" in the extension "Ati".
        /// </summary>
        public static partial class Ati
        {
            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glGetVertexAttribArrayObjectfvATI")]
            public static void GetVertexAttribArrayObject(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] float[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glGetVertexAttribArrayObjectfvATI")]
            public static void GetVertexAttribArrayObject(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] out float @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glGetVertexAttribArrayObjectfvATI")]
            public static unsafe void GetVertexAttribArrayObject(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] float* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glGetVertexAttribArrayObjectivATI")]
            public static void GetVertexAttribArrayObject(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glGetVertexAttribArrayObjectivATI")]
            public static void GetVertexAttribArrayObject(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glGetVertexAttribArrayObjectivATI")]
            public static unsafe void GetVertexAttribArrayObject(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_attrib_array_object]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="normalized">
            /// </param>
            /// <param name="stride">
            /// </param>
            /// <param name="buffer">
            /// </param>
            /// <param name="offset">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_attrib_array_object", Version = "", EntryPoint = "glVertexAttribArrayObjectATI")]
            public static void VertexAttribArrayObject(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, bool normalized, int stride, uint buffer, uint offset)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1126)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVertexAttribArrayObjectfvATI(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] float* @params);

            [Slot(1127)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVertexAttribArrayObjectivATI(uint index, OpenTK.Graphics.OpenGL.AtiVertexAttribArrayObject pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params);

            [Slot(2703)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribArrayObjectATI(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, bool normalized, int stride, uint buffer, uint offset);
        }
    }
}
