//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "VertexStreams" in the extension "Ati".
        /// </summary>
        public static partial class Ati
        {
            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glClientActiveVertexStreamATI")]
            public static void ClientActiveVertexStream(OpenTK.Graphics.OpenGL.AtiVertexStreams stream)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="nx">
            /// </param>
            /// <param name="ny">
            /// </param>
            /// <param name="nz">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3bATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, SByte nx, SByte ny, SByte nz)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3bvATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] SByte[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3bvATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref SByte coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3bvATI")]
            public static unsafe void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] SByte* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="nx">
            /// </param>
            /// <param name="ny">
            /// </param>
            /// <param name="nz">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3dATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double nx, double ny, double nz)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3dvATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] double[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3dvATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref double coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3dvATI")]
            public static unsafe void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] double* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="nx">
            /// </param>
            /// <param name="ny">
            /// </param>
            /// <param name="nz">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3fATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float nx, float ny, float nz)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3fvATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] float[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3fvATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref float coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3fvATI")]
            public static unsafe void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] float* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="nx">
            /// </param>
            /// <param name="ny">
            /// </param>
            /// <param name="nz">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3iATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int nx, int ny, int nz)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3ivATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] int[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3ivATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref int coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3ivATI")]
            public static unsafe void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] int* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="nx">
            /// </param>
            /// <param name="ny">
            /// </param>
            /// <param name="nz">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3sATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short nx, short ny, short nz)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3svATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] short[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3svATI")]
            public static void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref short coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glNormalStream3svATI")]
            public static unsafe void NormalStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] short* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexBlendEnvfATI")]
            public static void VertexBlendEnv(OpenTK.Graphics.OpenGL.AtiVertexStreams pname, float param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="pname">
            /// </param>
            /// <param name="param">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexBlendEnviATI")]
            public static void VertexBlendEnv(OpenTK.Graphics.OpenGL.AtiVertexStreams pname, int param)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1dATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1dvATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] ref double coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1dvATI")]
            public static unsafe void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] double* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1fATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1fvATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] ref float coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1fvATI")]
            public static unsafe void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] float* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1iATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1ivATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] ref int coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1ivATI")]
            public static unsafe void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] int* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1sATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1svATI")]
            public static void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] ref short coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream1svATI")]
            public static unsafe void VertexStream1(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] short* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2dATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x, double y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2dvATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] double[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2dvATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] ref double coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2dvATI")]
            public static unsafe void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] double* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2fATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x, float y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2fvATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] float[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2fvATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] ref float coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2fvATI")]
            public static unsafe void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] float* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2iATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x, int y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2ivATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] int[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2ivATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] ref int coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2ivATI")]
            public static unsafe void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] int* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2sATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x, short y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2svATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] short[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2svATI")]
            public static void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] ref short coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream2svATI")]
            public static unsafe void VertexStream2(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] short* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3dATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x, double y, double z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3dvATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] double[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3dvATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref double coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3dvATI")]
            public static unsafe void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] double* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3fATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x, float y, float z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3fvATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] float[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3fvATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref float coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3fvATI")]
            public static unsafe void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] float* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3iATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x, int y, int z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3ivATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] int[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3ivATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref int coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3ivATI")]
            public static unsafe void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] int* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3sATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x, short y, short z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3svATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] short[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3svATI")]
            public static void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] ref short coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream3svATI")]
            public static unsafe void VertexStream3(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] short* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4dATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x, double y, double z, double w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4dvATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] double[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4dvATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] ref double coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4dvATI")]
            public static unsafe void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] double* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4fATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x, float y, float z, float w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4fvATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] float[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4fvATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] ref float coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4fvATI")]
            public static unsafe void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] float* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4iATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x, int y, int z, int w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4ivATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] int[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4ivATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] ref int coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4ivATI")]
            public static unsafe void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] int* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4sATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x, short y, short z, short w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4svATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] short[] coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4svATI")]
            public static void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] ref short coords)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: ATI_vertex_streams]
            /// </summary>
            /// <param name="stream">
            /// </param>
            /// <param name="coords">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "ATI_vertex_streams", Version = "", EntryPoint = "glVertexStream4svATI")]
            public static unsafe void VertexStream4(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] short* coords)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(186)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glClientActiveVertexStreamATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream);

            [Slot(1624)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glNormalStream3bATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, SByte nx, SByte ny, SByte nz);

            [Slot(1625)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glNormalStream3bvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] SByte* coords);

            [Slot(1626)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glNormalStream3dATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double nx, double ny, double nz);

            [Slot(1627)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glNormalStream3dvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] double* coords);

            [Slot(1628)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glNormalStream3fATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float nx, float ny, float nz);

            [Slot(1629)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glNormalStream3fvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] float* coords);

            [Slot(1630)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glNormalStream3iATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int nx, int ny, int nz);

            [Slot(1631)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glNormalStream3ivATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] int* coords);

            [Slot(1632)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glNormalStream3sATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short nx, short ny, short nz);

            [Slot(1633)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glNormalStream3svATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] short* coords);

            [Slot(2822)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexBlendEnvfATI(OpenTK.Graphics.OpenGL.AtiVertexStreams pname, float param);

            [Slot(2823)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexBlendEnviATI(OpenTK.Graphics.OpenGL.AtiVertexStreams pname, int param);

            [Slot(2835)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream1dATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x);

            [Slot(2836)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream1dvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] double* coords);

            [Slot(2837)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream1fATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x);

            [Slot(2838)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream1fvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] float* coords);

            [Slot(2839)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream1iATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x);

            [Slot(2840)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream1ivATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] int* coords);

            [Slot(2841)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream1sATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x);

            [Slot(2842)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream1svATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 1)] short* coords);

            [Slot(2843)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream2dATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x, double y);

            [Slot(2844)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream2dvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] double* coords);

            [Slot(2845)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream2fATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x, float y);

            [Slot(2846)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream2fvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] float* coords);

            [Slot(2847)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream2iATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x, int y);

            [Slot(2848)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream2ivATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] int* coords);

            [Slot(2849)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream2sATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x, short y);

            [Slot(2850)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream2svATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 2)] short* coords);

            [Slot(2851)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream3dATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x, double y, double z);

            [Slot(2852)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream3dvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] double* coords);

            [Slot(2853)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream3fATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x, float y, float z);

            [Slot(2854)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream3fvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] float* coords);

            [Slot(2855)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream3iATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x, int y, int z);

            [Slot(2856)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream3ivATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] int* coords);

            [Slot(2857)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream3sATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x, short y, short z);

            [Slot(2858)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream3svATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 3)] short* coords);

            [Slot(2859)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream4dATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, double x, double y, double z, double w);

            [Slot(2860)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream4dvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] double* coords);

            [Slot(2861)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream4fATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, float x, float y, float z, float w);

            [Slot(2862)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream4fvATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] float* coords);

            [Slot(2863)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream4iATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, int x, int y, int z, int w);

            [Slot(2864)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream4ivATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] int* coords);

            [Slot(2865)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexStream4sATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, short x, short y, short z, short w);

            [Slot(2866)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexStream4svATI(OpenTK.Graphics.OpenGL.AtiVertexStreams stream, [CountAttribute(Count = 4)] short* coords);
        }
    }
}
