cl_command_queue_properties, CommandQueuePropertiesFlags
cl_queue_properties, CommandQueuePropertiesFlags # QueuePropertiesFlags does not exist in the specs
cl_device_type, DeviceTypeFlags
cl_image_desc, ImageDescriptor
cl_image_format, ImageFormat
cl_pipe_properties, IntPtr
