//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "DirectStateAccess|EXTDrawBuffers2" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glDisableIndexedEXT")]
            public static void DisableIndexed(OpenTK.Graphics.OpenGL.IndexedEnableCap target, uint index)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glEnableIndexedEXT")]
            public static void EnableIndexed(OpenTK.Graphics.OpenGL.IndexedEnableCap target, uint index)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glGetBooleanIndexedvEXT")]
            public static void GetBooleanIndexed(OpenTK.Graphics.OpenGL.BufferTargetArb target, uint index, [OutAttribute, CountAttribute(Computed = "target")] bool[] data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glGetBooleanIndexedvEXT")]
            public static void GetBooleanIndexed(OpenTK.Graphics.OpenGL.BufferTargetArb target, uint index, [OutAttribute, CountAttribute(Computed = "target")] out bool data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glGetBooleanIndexedvEXT")]
            public static unsafe void GetBooleanIndexed(OpenTK.Graphics.OpenGL.BufferTargetArb target, uint index, [OutAttribute, CountAttribute(Computed = "target")] bool* data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glGetIntegerIndexedvEXT")]
            public static void GetIntegerIndexed(OpenTK.Graphics.OpenGL.GetIndexedPName target, uint index, [OutAttribute, CountAttribute(Computed = "target")] int[] data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glGetIntegerIndexedvEXT")]
            public static void GetIntegerIndexed(OpenTK.Graphics.OpenGL.GetIndexedPName target, uint index, [OutAttribute, CountAttribute(Computed = "target")] out int data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="data">
            /// [length: COMPSIZE(target)]
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glGetIntegerIndexedvEXT")]
            public static unsafe void GetIntegerIndexed(OpenTK.Graphics.OpenGL.GetIndexedPName target, uint index, [OutAttribute, CountAttribute(Computed = "target")] int* data)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_direct_state_access|EXT_draw_buffers2]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            [AutoGenerated(Category = "EXT_direct_state_access|EXT_draw_buffers2", Version = "", EntryPoint = "glIsEnabledIndexedEXT")]
            public static bool IsEnabledIndexed(OpenTK.Graphics.OpenGL.IndexedEnableCap target, uint index)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(463)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDisableIndexedEXT(OpenTK.Graphics.OpenGL.IndexedEnableCap target, uint index);

            [Slot(527)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glEnableIndexedEXT(OpenTK.Graphics.OpenGL.IndexedEnableCap target, uint index);

            [Slot(715)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetBooleanIndexedvEXT(OpenTK.Graphics.OpenGL.BufferTargetArb target, uint index, [OutAttribute, CountAttribute(Computed = "target")] bool* data);

            [Slot(809)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetIntegerIndexedvEXT(OpenTK.Graphics.OpenGL.GetIndexedPName target, uint index, [OutAttribute, CountAttribute(Computed = "target")] int* data);

            [Slot(1222)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern byte glIsEnabledIndexedEXT(OpenTK.Graphics.OpenGL.IndexedEnableCap target, uint index);
        }
    }
}
