//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "VertexProgram4" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glGetVertexAttribIivEXT")]
            public static void GetVertexAttribI(uint index, OpenTK.Graphics.OpenGL.VertexAttribEnum pname, [OutAttribute, CountAttribute(Count = 1)] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glGetVertexAttribIivEXT")]
            public static unsafe void GetVertexAttribI(uint index, OpenTK.Graphics.OpenGL.VertexAttribEnum pname, [OutAttribute, CountAttribute(Count = 1)] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glGetVertexAttribIuivEXT")]
            public static void GetVertexAttribI(uint index, OpenTK.Graphics.OpenGL.VertexAttribEnum pname, [OutAttribute, CountAttribute(Count = 1)] out uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glGetVertexAttribIuivEXT")]
            public static unsafe void GetVertexAttribI(uint index, OpenTK.Graphics.OpenGL.VertexAttribEnum pname, [OutAttribute, CountAttribute(Count = 1)] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI1iEXT")]
            public static void VertexAttribI1(uint index, int x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI1ivEXT")]
            public static void VertexAttribI1(uint index, [CountAttribute(Count = 1)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI1ivEXT")]
            public static unsafe void VertexAttribI1(uint index, [CountAttribute(Count = 1)] int* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI1uiEXT")]
            public static void VertexAttribI1(uint index, uint x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI1uivEXT")]
            public static void VertexAttribI1(uint index, [CountAttribute(Count = 1)] ref uint v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI1uivEXT")]
            public static unsafe void VertexAttribI1(uint index, [CountAttribute(Count = 1)] uint* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2iEXT")]
            public static void VertexAttribI2(uint index, int x, int y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2ivEXT")]
            public static void VertexAttribI2(uint index, [CountAttribute(Count = 2)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2ivEXT")]
            public static void VertexAttribI2(uint index, [CountAttribute(Count = 2)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2ivEXT")]
            public static unsafe void VertexAttribI2(uint index, [CountAttribute(Count = 2)] int* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2uiEXT")]
            public static void VertexAttribI2(uint index, uint x, uint y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2uivEXT")]
            public static void VertexAttribI2(uint index, [CountAttribute(Count = 2)] uint[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2uivEXT")]
            public static void VertexAttribI2(uint index, [CountAttribute(Count = 2)] ref uint v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI2uivEXT")]
            public static unsafe void VertexAttribI2(uint index, [CountAttribute(Count = 2)] uint* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3iEXT")]
            public static void VertexAttribI3(uint index, int x, int y, int z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3ivEXT")]
            public static void VertexAttribI3(uint index, [CountAttribute(Count = 3)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3ivEXT")]
            public static void VertexAttribI3(uint index, [CountAttribute(Count = 3)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3ivEXT")]
            public static unsafe void VertexAttribI3(uint index, [CountAttribute(Count = 3)] int* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3uiEXT")]
            public static void VertexAttribI3(uint index, uint x, uint y, uint z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3uivEXT")]
            public static void VertexAttribI3(uint index, [CountAttribute(Count = 3)] uint[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3uivEXT")]
            public static void VertexAttribI3(uint index, [CountAttribute(Count = 3)] ref uint v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI3uivEXT")]
            public static unsafe void VertexAttribI3(uint index, [CountAttribute(Count = 3)] uint* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4bvEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] SByte[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4bvEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ref SByte v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4bvEXT")]
            public static unsafe void VertexAttribI4(uint index, [CountAttribute(Count = 4)] SByte* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4iEXT")]
            public static void VertexAttribI4(uint index, int x, int y, int z, int w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4ivEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] int[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4ivEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ref int v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4ivEXT")]
            public static unsafe void VertexAttribI4(uint index, [CountAttribute(Count = 4)] int* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4svEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] short[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4svEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ref short v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4svEXT")]
            public static unsafe void VertexAttribI4(uint index, [CountAttribute(Count = 4)] short* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4ubvEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] Byte[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4ubvEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ref Byte v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4ubvEXT")]
            public static unsafe void VertexAttribI4(uint index, [CountAttribute(Count = 4)] Byte* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4uiEXT")]
            public static void VertexAttribI4(uint index, uint x, uint y, uint z, uint w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4uivEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] uint[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4uivEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ref uint v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4uivEXT")]
            public static unsafe void VertexAttribI4(uint index, [CountAttribute(Count = 4)] uint* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4usvEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ushort[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4usvEXT")]
            public static void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ref ushort v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribI4usvEXT")]
            public static unsafe void VertexAttribI4(uint index, [CountAttribute(Count = 4)] ushort* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="stride">
            /// </param>
            /// <param name="pointer">
            /// [length: COMPSIZE(size,type,stride)]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribIPointerEXT")]
            public static void VertexAttribIPointer(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, int stride, [CountAttribute(Computed = "size,type,stride")] IntPtr pointer)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="stride">
            /// </param>
            /// <param name="pointer">
            /// [length: COMPSIZE(size,type,stride)]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribIPointerEXT")]
            public static void VertexAttribIPointer<T4>(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, int stride, [InAttribute, OutAttribute, CountAttribute(Computed = "size,type,stride")] T4[] pointer)
                where T4 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="stride">
            /// </param>
            /// <param name="pointer">
            /// [length: COMPSIZE(size,type,stride)]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribIPointerEXT")]
            public static void VertexAttribIPointer<T4>(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, int stride, [InAttribute, OutAttribute, CountAttribute(Computed = "size,type,stride")] T4[,] pointer)
                where T4 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="stride">
            /// </param>
            /// <param name="pointer">
            /// [length: COMPSIZE(size,type,stride)]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribIPointerEXT")]
            public static void VertexAttribIPointer<T4>(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, int stride, [InAttribute, OutAttribute, CountAttribute(Computed = "size,type,stride")] T4[,,] pointer)
                where T4 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_vertex_program4]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="size">
            /// </param>
            /// <param name="type">
            /// </param>
            /// <param name="stride">
            /// </param>
            /// <param name="pointer">
            /// [length: COMPSIZE(size,type,stride)]
            /// </param>
            [AutoGenerated(Category = "NV_vertex_program4", Version = "", EntryPoint = "glVertexAttribIPointerEXT")]
            public static void VertexAttribIPointer<T4>(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, int stride, [InAttribute, OutAttribute, CountAttribute(Computed = "size,type,stride")] ref T4 pointer)
                where T4 : struct
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1135)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVertexAttribIivEXT(uint index, OpenTK.Graphics.OpenGL.VertexAttribEnum pname, [OutAttribute, CountAttribute(Count = 1)] int* @params);

            [Slot(1137)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVertexAttribIuivEXT(uint index, OpenTK.Graphics.OpenGL.VertexAttribEnum pname, [OutAttribute, CountAttribute(Count = 1)] uint* @params);

            [Slot(2710)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI1iEXT(uint index, int x);

            [Slot(2712)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI1ivEXT(uint index, [CountAttribute(Count = 1)] int* v);

            [Slot(2714)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI1uiEXT(uint index, uint x);

            [Slot(2716)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI1uivEXT(uint index, [CountAttribute(Count = 1)] uint* v);

            [Slot(2718)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI2iEXT(uint index, int x, int y);

            [Slot(2720)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI2ivEXT(uint index, [CountAttribute(Count = 2)] int* v);

            [Slot(2722)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI2uiEXT(uint index, uint x, uint y);

            [Slot(2724)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI2uivEXT(uint index, [CountAttribute(Count = 2)] uint* v);

            [Slot(2726)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI3iEXT(uint index, int x, int y, int z);

            [Slot(2728)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI3ivEXT(uint index, [CountAttribute(Count = 3)] int* v);

            [Slot(2730)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI3uiEXT(uint index, uint x, uint y, uint z);

            [Slot(2732)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI3uivEXT(uint index, [CountAttribute(Count = 3)] uint* v);

            [Slot(2734)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI4bvEXT(uint index, [CountAttribute(Count = 4)] SByte* v);

            [Slot(2736)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI4iEXT(uint index, int x, int y, int z, int w);

            [Slot(2738)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI4ivEXT(uint index, [CountAttribute(Count = 4)] int* v);

            [Slot(2740)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI4svEXT(uint index, [CountAttribute(Count = 4)] short* v);

            [Slot(2742)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI4ubvEXT(uint index, [CountAttribute(Count = 4)] Byte* v);

            [Slot(2744)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribI4uiEXT(uint index, uint x, uint y, uint z, uint w);

            [Slot(2746)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI4uivEXT(uint index, [CountAttribute(Count = 4)] uint* v);

            [Slot(2748)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribI4usvEXT(uint index, [CountAttribute(Count = 4)] ushort* v);

            [Slot(2752)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttribIPointerEXT(uint index, int size, OpenTK.Graphics.OpenGL.VertexAttribPointerType type, int stride, [CountAttribute(Computed = "size,type,stride")] IntPtr pointer);
        }
    }
}
