//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "DepthBufferFloat" in the extension "NV".
        /// </summary>
        public static partial class NV
        {
            /// <summary>
            /// [requires: NV_depth_buffer_float]
            /// Specify the clear value for the depth buffer
            /// </summary>
            /// <param name="depth">
            /// Specifies the depth value used when the depth buffer is cleared. The initial value is 1.
            /// </param>
            [AutoGenerated(Category = "NV_depth_buffer_float", Version = "", EntryPoint = "glClearDepthdNV")]
            public static void ClearDepth(double depth)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_depth_buffer_float]
            /// </summary>
            /// <param name="zmin">
            /// </param>
            /// <param name="zmax">
            /// </param>
            [AutoGenerated(Category = "NV_depth_buffer_float", Version = "", EntryPoint = "glDepthBoundsdNV")]
            public static void DepthBounds(double zmin, double zmax)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_depth_buffer_float]
            /// Specify mapping of depth values from normalized device coordinates to window coordinates
            /// </summary>
            /// <param name="zNear">
            /// Specifies the mapping of the near clipping plane to window coordinates. The initial value is 0.
            /// </param>
            /// <param name="zFar">
            /// Specifies the mapping of the far clipping plane to window coordinates. The initial value is 1.
            /// </param>
            [AutoGenerated(Category = "NV_depth_buffer_float", Version = "", EntryPoint = "glDepthRangedNV")]
            public static void DepthRange(double zNear, double zFar)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(168)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glClearDepthdNV(double depth);

            [Slot(444)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDepthBoundsdNV(double zmin, double zmax);

            [Slot(450)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glDepthRangedNV(double zNear, double zFar);
        }
    }
}
