//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "GpuProgram4" in the extension "NV".
        /// </summary>
        public static partial class NV
        {
            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramEnvParameterIivNV")]
            public static void GetProgramEnvParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramEnvParameterIivNV")]
            public static void GetProgramEnvParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramEnvParameterIivNV")]
            public static unsafe void GetProgramEnvParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramEnvParameterIuivNV")]
            public static void GetProgramEnvParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramEnvParameterIuivNV")]
            public static void GetProgramEnvParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] out uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramEnvParameterIuivNV")]
            public static unsafe void GetProgramEnvParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramLocalParameterIivNV")]
            public static void GetProgramLocalParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramLocalParameterIivNV")]
            public static void GetProgramLocalParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramLocalParameterIivNV")]
            public static unsafe void GetProgramLocalParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramLocalParameterIuivNV")]
            public static void GetProgramLocalParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramLocalParameterIuivNV")]
            public static void GetProgramLocalParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] out uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glGetProgramLocalParameterIuivNV")]
            public static unsafe void GetProgramLocalParameterI(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4iNV")]
            public static void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int x, int y, int z, int w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4ivNV")]
            public static void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4ivNV")]
            public static void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4ivNV")]
            public static unsafe void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4uiNV")]
            public static void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, uint x, uint y, uint z, uint w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4uivNV")]
            public static void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4uivNV")]
            public static void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] ref uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParameterI4uivNV")]
            public static unsafe void ProgramEnvParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParametersI4ivNV")]
            public static void ProgramEnvParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParametersI4ivNV")]
            public static void ProgramEnvParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParametersI4ivNV")]
            public static unsafe void ProgramEnvParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParametersI4uivNV")]
            public static void ProgramEnvParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParametersI4uivNV")]
            public static void ProgramEnvParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] ref uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramEnvParametersI4uivNV")]
            public static unsafe void ProgramEnvParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4iNV")]
            public static void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int x, int y, int z, int w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4ivNV")]
            public static void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4ivNV")]
            public static void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4ivNV")]
            public static unsafe void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4uiNV")]
            public static void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, uint x, uint y, uint z, uint w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4uivNV")]
            public static void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4uivNV")]
            public static void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] ref uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="@params">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParameterI4uivNV")]
            public static unsafe void ProgramLocalParameterI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParametersI4ivNV")]
            public static void ProgramLocalParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParametersI4ivNV")]
            public static void ProgramLocalParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParametersI4ivNV")]
            public static unsafe void ProgramLocalParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParametersI4uivNV")]
            public static void ProgramLocalParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParametersI4uivNV")]
            public static void ProgramLocalParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] ref uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_gpu_program4]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count*4]
            /// </param>
            [AutoGenerated(Category = "NV_gpu_program4", Version = "", EntryPoint = "glProgramLocalParametersI4uivNV")]
            public static unsafe void ProgramLocalParametersI4(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(979)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetProgramEnvParameterIivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] int* @params);

            [Slot(980)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetProgramEnvParameterIuivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] uint* @params);

            [Slot(988)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetProgramLocalParameterIivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] int* @params);

            [Slot(989)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetProgramLocalParameterIuivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [OutAttribute, CountAttribute(Count = 4)] uint* @params);

            [Slot(1745)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glProgramEnvParameterI4iNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int x, int y, int z, int w);

            [Slot(1746)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramEnvParameterI4ivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] int* @params);

            [Slot(1747)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glProgramEnvParameterI4uiNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, uint x, uint y, uint z, uint w);

            [Slot(1748)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramEnvParameterI4uivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] uint* @params);

            [Slot(1750)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramEnvParametersI4ivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] int* @params);

            [Slot(1751)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramEnvParametersI4uivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] uint* @params);

            [Slot(1756)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glProgramLocalParameterI4iNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int x, int y, int z, int w);

            [Slot(1757)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramLocalParameterI4ivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] int* @params);

            [Slot(1758)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glProgramLocalParameterI4uiNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, uint x, uint y, uint z, uint w);

            [Slot(1759)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramLocalParameterI4uivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, [CountAttribute(Count = 4)] uint* @params);

            [Slot(1761)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramLocalParametersI4ivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] int* @params);

            [Slot(1762)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramLocalParametersI4uivNV(OpenTK.Graphics.OpenGL.NvGpuProgram4 target, uint index, int count, [CountAttribute(Parameter = "count*4")] uint* @params);
        }
    }
}
