//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "HalfFloat" in the extension "NV".
        /// </summary>
        public static partial class NV
        {
            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="red">
            /// </param>
            /// <param name="green">
            /// </param>
            /// <param name="blue">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glColor3hNV")]
            public static void Color3h(Half red, Half green, Half blue)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glColor3hvNV")]
            public static void Color3h([CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glColor3hvNV")]
            public static void Color3h([CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="red">
            /// </param>
            /// <param name="green">
            /// </param>
            /// <param name="blue">
            /// </param>
            /// <param name="alpha">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glColor4hNV")]
            public static void Color4h(Half red, Half green, Half blue, Half alpha)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glColor4hvNV")]
            public static void Color4h([CountAttribute(Count = 4)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glColor4hvNV")]
            public static void Color4h([CountAttribute(Count = 4)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="fog">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glFogCoordhNV")]
            public static void FogCoordh(Half fog)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="fog">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glFogCoordhvNV")]
            public static void FogCoordh([CountAttribute(Count = 1)] ref Half fog)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="s">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord1hNV")]
            public static void MultiTexCoord1h(OpenTK.Graphics.OpenGL.TextureUnit target, Half s)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord1hvNV")]
            public static void MultiTexCoord1h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 1)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord1hvNV")]
            public static unsafe void MultiTexCoord1h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 1)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="s">
            /// </param>
            /// <param name="t">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord2hNV")]
            public static void MultiTexCoord2h(OpenTK.Graphics.OpenGL.TextureUnit target, Half s, Half t)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord2hvNV")]
            public static void MultiTexCoord2h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 2)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord2hvNV")]
            public static void MultiTexCoord2h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 2)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord2hvNV")]
            public static unsafe void MultiTexCoord2h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 2)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="s">
            /// </param>
            /// <param name="t">
            /// </param>
            /// <param name="r">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord3hNV")]
            public static void MultiTexCoord3h(OpenTK.Graphics.OpenGL.TextureUnit target, Half s, Half t, Half r)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord3hvNV")]
            public static void MultiTexCoord3h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord3hvNV")]
            public static void MultiTexCoord3h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord3hvNV")]
            public static unsafe void MultiTexCoord3h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 3)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="s">
            /// </param>
            /// <param name="t">
            /// </param>
            /// <param name="r">
            /// </param>
            /// <param name="q">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord4hNV")]
            public static void MultiTexCoord4h(OpenTK.Graphics.OpenGL.TextureUnit target, Half s, Half t, Half r, Half q)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord4hvNV")]
            public static void MultiTexCoord4h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 4)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord4hvNV")]
            public static void MultiTexCoord4h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 4)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glMultiTexCoord4hvNV")]
            public static unsafe void MultiTexCoord4h(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 4)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="nx">
            /// </param>
            /// <param name="ny">
            /// </param>
            /// <param name="nz">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glNormal3hNV")]
            public static void Normal3h(Half nx, Half ny, Half nz)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glNormal3hvNV")]
            public static void Normal3h([CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glNormal3hvNV")]
            public static void Normal3h([CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="red">
            /// </param>
            /// <param name="green">
            /// </param>
            /// <param name="blue">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glSecondaryColor3hNV")]
            public static void SecondaryColor3h(Half red, Half green, Half blue)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glSecondaryColor3hvNV")]
            public static void SecondaryColor3h([CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glSecondaryColor3hvNV")]
            public static void SecondaryColor3h([CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="s">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord1hNV")]
            public static void TexCoord1h(Half s)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord1hvNV")]
            public static void TexCoord1h([CountAttribute(Count = 1)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="s">
            /// </param>
            /// <param name="t">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord2hNV")]
            public static void TexCoord2h(Half s, Half t)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord2hvNV")]
            public static void TexCoord2h([CountAttribute(Count = 2)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord2hvNV")]
            public static void TexCoord2h([CountAttribute(Count = 2)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="s">
            /// </param>
            /// <param name="t">
            /// </param>
            /// <param name="r">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord3hNV")]
            public static void TexCoord3h(Half s, Half t, Half r)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord3hvNV")]
            public static void TexCoord3h([CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord3hvNV")]
            public static void TexCoord3h([CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="s">
            /// </param>
            /// <param name="t">
            /// </param>
            /// <param name="r">
            /// </param>
            /// <param name="q">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord4hNV")]
            public static void TexCoord4h(Half s, Half t, Half r, Half q)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord4hvNV")]
            public static void TexCoord4h([CountAttribute(Count = 4)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glTexCoord4hvNV")]
            public static void TexCoord4h([CountAttribute(Count = 4)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex2hNV")]
            public static void Vertex2h(Half x, Half y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex2hvNV")]
            public static void Vertex2h([CountAttribute(Count = 2)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex2hvNV")]
            public static void Vertex2h([CountAttribute(Count = 2)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex3hNV")]
            public static void Vertex3h(Half x, Half y, Half z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex3hvNV")]
            public static void Vertex3h([CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex3hvNV")]
            public static void Vertex3h([CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex4hNV")]
            public static void Vertex4h(Half x, Half y, Half z, Half w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex4hvNV")]
            public static void Vertex4h([CountAttribute(Count = 4)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertex4hvNV")]
            public static void Vertex4h([CountAttribute(Count = 4)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib1hNV")]
            public static void VertexAttrib1h(uint index, Half x)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib1hvNV")]
            public static void VertexAttrib1h(uint index, [CountAttribute(Count = 1)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib1hvNV")]
            public static unsafe void VertexAttrib1h(uint index, [CountAttribute(Count = 1)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib2hNV")]
            public static void VertexAttrib2h(uint index, Half x, Half y)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib2hvNV")]
            public static void VertexAttrib2h(uint index, [CountAttribute(Count = 2)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib2hvNV")]
            public static void VertexAttrib2h(uint index, [CountAttribute(Count = 2)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 2]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib2hvNV")]
            public static unsafe void VertexAttrib2h(uint index, [CountAttribute(Count = 2)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib3hNV")]
            public static void VertexAttrib3h(uint index, Half x, Half y, Half z)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib3hvNV")]
            public static void VertexAttrib3h(uint index, [CountAttribute(Count = 3)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib3hvNV")]
            public static void VertexAttrib3h(uint index, [CountAttribute(Count = 3)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 3]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib3hvNV")]
            public static unsafe void VertexAttrib3h(uint index, [CountAttribute(Count = 3)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="x">
            /// </param>
            /// <param name="y">
            /// </param>
            /// <param name="z">
            /// </param>
            /// <param name="w">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib4hNV")]
            public static void VertexAttrib4h(uint index, Half x, Half y, Half z, Half w)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib4hvNV")]
            public static void VertexAttrib4h(uint index, [CountAttribute(Count = 4)] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib4hvNV")]
            public static void VertexAttrib4h(uint index, [CountAttribute(Count = 4)] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="v">
            /// [length: 4]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttrib4hvNV")]
            public static unsafe void VertexAttrib4h(uint index, [CountAttribute(Count = 4)] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs1hvNV")]
            public static void VertexAttribs1h(uint index, int n, [CountAttribute(Parameter = "n")] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs1hvNV")]
            public static void VertexAttribs1h(uint index, int n, [CountAttribute(Parameter = "n")] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs1hvNV")]
            public static unsafe void VertexAttribs1h(uint index, int n, [CountAttribute(Parameter = "n")] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs2hvNV")]
            public static void VertexAttribs2h(uint index, int n, [CountAttribute(Parameter = "n")] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs2hvNV")]
            public static void VertexAttribs2h(uint index, int n, [CountAttribute(Parameter = "n")] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs2hvNV")]
            public static unsafe void VertexAttribs2h(uint index, int n, [CountAttribute(Parameter = "n")] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs3hvNV")]
            public static void VertexAttribs3h(uint index, int n, [CountAttribute(Parameter = "n")] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs3hvNV")]
            public static void VertexAttribs3h(uint index, int n, [CountAttribute(Parameter = "n")] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs3hvNV")]
            public static unsafe void VertexAttribs3h(uint index, int n, [CountAttribute(Parameter = "n")] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs4hvNV")]
            public static void VertexAttribs4h(uint index, int n, [CountAttribute(Parameter = "n")] Half[] v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs4hvNV")]
            public static void VertexAttribs4h(uint index, int n, [CountAttribute(Parameter = "n")] ref Half v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="index">
            /// </param>
            /// <param name="n">
            /// </param>
            /// <param name="v">
            /// [length: n]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexAttribs4hvNV")]
            public static unsafe void VertexAttribs4h(uint index, int n, [CountAttribute(Parameter = "n")] Half* v)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="weight">
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexWeighthNV")]
            public static void VertexWeighth(Half weight)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_half_float]
            /// </summary>
            /// <param name="weight">
            /// [length: 1]
            /// </param>
            [AutoGenerated(Category = "NV_half_float", Version = "", EntryPoint = "glVertexWeighthvNV")]
            public static void VertexWeighth([CountAttribute(Count = 1)] ref Half weight)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(201)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glColor3hNV(Half red, Half green, Half blue);

            [Slot(202)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glColor3hvNV([CountAttribute(Count = 3)] Half* v);

            [Slot(223)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glColor4hNV(Half red, Half green, Half blue, Half alpha);

            [Slot(224)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glColor4hvNV([CountAttribute(Count = 4)] Half* v);

            [Slot(601)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glFogCoordhNV(Half fog);

            [Slot(602)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glFogCoordhvNV([CountAttribute(Count = 1)] Half* fog);

            [Slot(1434)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord1hNV(OpenTK.Graphics.OpenGL.TextureUnit target, Half s);

            [Slot(1435)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord1hvNV(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 1)] Half* v);

            [Slot(1456)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord2hNV(OpenTK.Graphics.OpenGL.TextureUnit target, Half s, Half t);

            [Slot(1457)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord2hvNV(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 2)] Half* v);

            [Slot(1478)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord3hNV(OpenTK.Graphics.OpenGL.TextureUnit target, Half s, Half t, Half r);

            [Slot(1479)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord3hvNV(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 3)] Half* v);

            [Slot(1500)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glMultiTexCoord4hNV(OpenTK.Graphics.OpenGL.TextureUnit target, Half s, Half t, Half r, Half q);

            [Slot(1501)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glMultiTexCoord4hvNV(OpenTK.Graphics.OpenGL.TextureUnit target, [CountAttribute(Count = 4)] Half* v);

            [Slot(1609)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glNormal3hNV(Half nx, Half ny, Half nz);

            [Slot(1610)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glNormal3hvNV([CountAttribute(Count = 3)] Half* v);

            [Slot(2060)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glSecondaryColor3hNV(Half red, Half green, Half blue);

            [Slot(2061)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glSecondaryColor3hvNV([CountAttribute(Count = 3)] Half* v);

            [Slot(2172)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord1hNV(Half s);

            [Slot(2173)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord1hvNV([CountAttribute(Count = 1)] Half* v);

            [Slot(2196)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord2hNV(Half s, Half t);

            [Slot(2197)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord2hvNV([CountAttribute(Count = 2)] Half* v);

            [Slot(2210)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord3hNV(Half s, Half t, Half r);

            [Slot(2211)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord3hvNV([CountAttribute(Count = 3)] Half* v);

            [Slot(2228)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexCoord4hNV(Half s, Half t, Half r, Half q);

            [Slot(2229)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glTexCoord4hvNV([CountAttribute(Count = 4)] Half* v);

            [Slot(2531)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertex2hNV(Half x, Half y);

            [Slot(2532)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertex2hvNV([CountAttribute(Count = 2)] Half* v);

            [Slot(2545)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertex3hNV(Half x, Half y, Half z);

            [Slot(2546)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertex3hvNV([CountAttribute(Count = 3)] Half* v);

            [Slot(2559)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertex4hNV(Half x, Half y, Half z, Half w);

            [Slot(2560)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertex4hvNV([CountAttribute(Count = 4)] Half* v);

            [Slot(2609)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttrib1hNV(uint index, Half x);

            [Slot(2610)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttrib1hvNV(uint index, [CountAttribute(Count = 1)] Half* v);

            [Slot(2629)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttrib2hNV(uint index, Half x, Half y);

            [Slot(2630)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttrib2hvNV(uint index, [CountAttribute(Count = 2)] Half* v);

            [Slot(2649)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttrib3hNV(uint index, Half x, Half y, Half z);

            [Slot(2650)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttrib3hvNV(uint index, [CountAttribute(Count = 3)] Half* v);

            [Slot(2671)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexAttrib4hNV(uint index, Half x, Half y, Half z, Half w);

            [Slot(2672)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttrib4hvNV(uint index, [CountAttribute(Count = 4)] Half* v);

            [Slot(2805)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribs1hvNV(uint index, int n, [CountAttribute(Parameter = "n")] Half* v);

            [Slot(2809)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribs2hvNV(uint index, int n, [CountAttribute(Parameter = "n")] Half* v);

            [Slot(2813)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribs3hvNV(uint index, int n, [CountAttribute(Parameter = "n")] Half* v);

            [Slot(2817)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexAttribs4hvNV(uint index, int n, [CountAttribute(Parameter = "n")] Half* v);

            [Slot(2869)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glVertexWeighthNV(Half weight);

            [Slot(2870)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVertexWeighthvNV([CountAttribute(Count = 1)] Half* weight);
        }
    }
}
