//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "ParameterBufferObject" in the extension "NV".
        /// </summary>
        public static partial class NV
        {
            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersIivNV")]
            public static void ProgramBufferParametersI(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersIivNV")]
            public static void ProgramBufferParametersI(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersIivNV")]
            public static unsafe void ProgramBufferParametersI(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersIuivNV")]
            public static void ProgramBufferParametersI(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] uint[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersIuivNV")]
            public static void ProgramBufferParametersI(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] ref uint @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersIuivNV")]
            public static unsafe void ProgramBufferParametersI(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] uint* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersfvNV")]
            public static void ProgramBufferParameters(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] float[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersfvNV")]
            public static void ProgramBufferParameters(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] ref float @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_parameter_buffer_object]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="bindingIndex">
            /// </param>
            /// <param name="wordIndex">
            /// </param>
            /// <param name="count">
            /// </param>
            /// <param name="@params">
            /// [length: count]
            /// </param>
            [AutoGenerated(Category = "NV_parameter_buffer_object", Version = "", EntryPoint = "glProgramBufferParametersfvNV")]
            public static unsafe void ProgramBufferParameters(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] float* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(1739)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramBufferParametersIivNV(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] int* @params);

            [Slot(1740)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramBufferParametersIuivNV(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] uint* @params);

            [Slot(1738)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glProgramBufferParametersfvNV(OpenTK.Graphics.OpenGL.NvParameterBufferObject target, uint bindingIndex, uint wordIndex, int count, [CountAttribute(Parameter = "count")] float* @params);
        }
    }
}
