//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "TextureMultisample" in the extension "NV".
        /// </summary>
        public static partial class NV
        {
            /// <summary>
            /// [requires: NV_texture_multisample]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="coverageSamples">
            /// </param>
            /// <param name="colorSamples">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="fixedSampleLocations">
            /// </param>
            [AutoGenerated(Category = "NV_texture_multisample", Version = "", EntryPoint = "glTexImage2DMultisampleCoverageNV")]
            public static void TexImage2DMultisampleCoverage(OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, bool fixedSampleLocations)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_texture_multisample]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="coverageSamples">
            /// </param>
            /// <param name="colorSamples">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="fixedSampleLocations">
            /// </param>
            [AutoGenerated(Category = "NV_texture_multisample", Version = "", EntryPoint = "glTexImage3DMultisampleCoverageNV")]
            public static void TexImage3DMultisampleCoverage(OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, int depth, bool fixedSampleLocations)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_texture_multisample]
            /// </summary>
            /// <param name="texture">
            /// </param>
            /// <param name="target">
            /// </param>
            /// <param name="coverageSamples">
            /// </param>
            /// <param name="colorSamples">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="fixedSampleLocations">
            /// </param>
            [AutoGenerated(Category = "NV_texture_multisample", Version = "", EntryPoint = "glTextureImage2DMultisampleCoverageNV")]
            public static void TextureImage2DMultisampleCoverage(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, bool fixedSampleLocations)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_texture_multisample]
            /// </summary>
            /// <param name="texture">
            /// </param>
            /// <param name="target">
            /// </param>
            /// <param name="samples">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="fixedSampleLocations">
            /// </param>
            [AutoGenerated(Category = "NV_texture_multisample", Version = "", EntryPoint = "glTextureImage2DMultisampleNV")]
            public static void TextureImage2DMultisample(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int samples, int internalFormat, int width, int height, bool fixedSampleLocations)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_texture_multisample]
            /// </summary>
            /// <param name="texture">
            /// </param>
            /// <param name="target">
            /// </param>
            /// <param name="coverageSamples">
            /// </param>
            /// <param name="colorSamples">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="fixedSampleLocations">
            /// </param>
            [AutoGenerated(Category = "NV_texture_multisample", Version = "", EntryPoint = "glTextureImage3DMultisampleCoverageNV")]
            public static void TextureImage3DMultisampleCoverage(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, int depth, bool fixedSampleLocations)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_texture_multisample]
            /// </summary>
            /// <param name="texture">
            /// </param>
            /// <param name="target">
            /// </param>
            /// <param name="samples">
            /// </param>
            /// <param name="internalFormat">
            /// </param>
            /// <param name="width">
            /// </param>
            /// <param name="height">
            /// </param>
            /// <param name="depth">
            /// </param>
            /// <param name="fixedSampleLocations">
            /// </param>
            [AutoGenerated(Category = "NV_texture_multisample", Version = "", EntryPoint = "glTextureImage3DMultisampleNV")]
            public static void TextureImage3DMultisample(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int samples, int internalFormat, int width, int height, int depth, bool fixedSampleLocations)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(2267)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexImage2DMultisampleCoverageNV(OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, bool fixedSampleLocations);

            [Slot(2271)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTexImage3DMultisampleCoverageNV(OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, int depth, bool fixedSampleLocations);

            [Slot(2312)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTextureImage2DMultisampleCoverageNV(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, bool fixedSampleLocations);

            [Slot(2313)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTextureImage2DMultisampleNV(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int samples, int internalFormat, int width, int height, bool fixedSampleLocations);

            [Slot(2315)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTextureImage3DMultisampleCoverageNV(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int coverageSamples, int colorSamples, int internalFormat, int width, int height, int depth, bool fixedSampleLocations);

            [Slot(2316)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glTextureImage3DMultisampleNV(uint texture, OpenTK.Graphics.OpenGL.TextureTarget target, int samples, int internalFormat, int width, int height, int depth, bool fixedSampleLocations);
        }
    }
}
