//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "VideoCapture" in the extension "NV".
        /// </summary>
        public static partial class NV
        {
            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glBeginVideoCaptureNV")]
            public static void BeginVideoCapture(uint video_capture_slot)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="frame_region">
            /// </param>
            /// <param name="offset">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glBindVideoCaptureStreamBufferNV")]
            public static void BindVideoCaptureStreamBuffer(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture frame_region, IntPtr offset)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="frame_region">
            /// </param>
            /// <param name="target">
            /// </param>
            /// <param name="texture">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glBindVideoCaptureStreamTextureNV")]
            public static void BindVideoCaptureStreamTexture(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture frame_region, OpenTK.Graphics.OpenGL.NvVideoCapture target, uint texture)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glEndVideoCaptureNV")]
            public static void EndVideoCapture(uint video_capture_slot)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamdvNV")]
            public static void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] double[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamdvNV")]
            public static void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] out double @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamdvNV")]
            public static unsafe void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] double* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamfvNV")]
            public static void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] float[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamfvNV")]
            public static void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] out float @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamfvNV")]
            public static unsafe void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] float* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamivNV")]
            public static void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamivNV")]
            public static void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureStreamivNV")]
            public static unsafe void GetVideoCaptureStream(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureivNV")]
            public static void GetVideoCapture(uint video_capture_slot, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureivNV")]
            public static void GetVideoCapture(uint video_capture_slot, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] out int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glGetVideoCaptureivNV")]
            public static unsafe void GetVideoCapture(uint video_capture_slot, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="sequence_num">
            /// </param>
            /// <param name="capture_time">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureNV")]
            public static OpenTK.Graphics.OpenGL.NvVideoCapture VideoCapture(uint video_capture_slot, [OutAttribute] uint[] sequence_num, [OutAttribute] ulong[] capture_time)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="sequence_num">
            /// </param>
            /// <param name="capture_time">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureNV")]
            public static OpenTK.Graphics.OpenGL.NvVideoCapture VideoCapture(uint video_capture_slot, [OutAttribute] out uint sequence_num, [OutAttribute] out ulong capture_time)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="sequence_num">
            /// </param>
            /// <param name="capture_time">
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureNV")]
            public static unsafe OpenTK.Graphics.OpenGL.NvVideoCapture VideoCapture(uint video_capture_slot, [OutAttribute] uint* sequence_num, [OutAttribute] ulong* capture_time)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterdvNV")]
            public static void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] double[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterdvNV")]
            public static void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] ref double @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterdvNV")]
            public static unsafe void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] double* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterfvNV")]
            public static void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] float[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterfvNV")]
            public static void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] ref float @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterfvNV")]
            public static unsafe void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] float* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterivNV")]
            public static void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] int[] @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterivNV")]
            public static void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] ref int @params)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: NV_video_capture]
            /// </summary>
            /// <param name="video_capture_slot">
            /// </param>
            /// <param name="stream">
            /// </param>
            /// <param name="pname">
            /// </param>
            /// <param name="@params">
            /// [length: COMPSIZE(pname)]
            /// </param>
            [AutoGenerated(Category = "NV_video_capture", Version = "", EntryPoint = "glVideoCaptureStreamParameterivNV")]
            public static unsafe void VideoCaptureStreamParameter(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] int* @params)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(42)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBeginVideoCaptureNV(uint video_capture_slot);

            [Slot(91)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBindVideoCaptureStreamBufferNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture frame_region, IntPtr offset);

            [Slot(92)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBindVideoCaptureStreamTextureNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture frame_region, OpenTK.Graphics.OpenGL.NvVideoCapture target, uint texture);

            [Slot(551)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glEndVideoCaptureNV(uint video_capture_slot);

            [Slot(1150)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVideoCaptureStreamdvNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] double* @params);

            [Slot(1151)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVideoCaptureStreamfvNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] float* @params);

            [Slot(1152)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVideoCaptureStreamivNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params);

            [Slot(1149)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glGetVideoCaptureivNV(uint video_capture_slot, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [OutAttribute, CountAttribute(Computed = "pname")] int* @params);

            [Slot(2872)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe OpenTK.Graphics.OpenGL.NvVideoCapture glVideoCaptureNV(uint video_capture_slot, [OutAttribute] uint* sequence_num, [OutAttribute] ulong* capture_time);

            [Slot(2873)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVideoCaptureStreamParameterdvNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] double* @params);

            [Slot(2874)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVideoCaptureStreamParameterfvNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] float* @params);

            [Slot(2875)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern unsafe void glVideoCaptureStreamParameterivNV(uint video_capture_slot, uint stream, OpenTK.Graphics.OpenGL.NvVideoCapture pname, [CountAttribute(Computed = "pname")] int* @params);
        }
    }
}
