//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES31
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "Multiview" in the extension "Ovr".
        /// </summary>
        public static partial class Ovr
        {
            /// <summary>
            /// [requires: OVR_multiview]
            /// </summary>
            /// <param name="target">
            /// </param>
            /// <param name="attachment">
            /// </param>
            /// <param name="texture">
            /// </param>
            /// <param name="level">
            /// </param>
            /// <param name="baseViewIndex">
            /// </param>
            /// <param name="numViews">
            /// </param>
            [AutoGenerated(Category = "OVR_multiview", Version = "", EntryPoint = "glFramebufferTextureMultiviewOVR")]
            public static void FramebufferTextureMultiview(OpenTK.Graphics.ES31.FramebufferTarget target, OpenTK.Graphics.ES31.FramebufferAttachment attachment, uint texture, int level, int baseViewIndex, int numViews)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(233)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glFramebufferTextureMultiviewOVR(OpenTK.Graphics.ES31.FramebufferTarget target, OpenTK.Graphics.ES31.FramebufferAttachment attachment, uint texture, int level, int baseViewIndex, int numViews);
        }
    }
}
