//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.ES30
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "BlendFuncExtended" in the extension "Ext".
        /// </summary>
        public static partial class Ext
        {
            /// <summary>
            /// [requires: EXT_blend_func_extended]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="color">
            /// </param>
            /// <param name="name">
            /// [length: COMPSIZE(name)]
            /// </param>
            [AutoGenerated(Category = "EXT_blend_func_extended", Version = "", EntryPoint = "glBindFragDataLocationEXT")]
            public static void BindFragDataLocation(uint program, uint color, [CountAttribute(Computed = "name")] String name)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_blend_func_extended]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="colorNumber">
            /// </param>
            /// <param name="index">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_blend_func_extended", Version = "", EntryPoint = "glBindFragDataLocationIndexedEXT")]
            public static void BindFragDataLocationIndexed(uint program, uint colorNumber, uint index, String name)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_blend_func_extended]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="name">
            /// </param>
            [AutoGenerated(Category = "EXT_blend_func_extended", Version = "", EntryPoint = "glGetFragDataIndexEXT")]
            public static int GetFragDataIndex(uint program, String name)
            {
                throw new BindingsNotRewrittenException();
            }

            /// <summary>
            /// [requires: EXT_blend_func_extended]
            /// </summary>
            /// <param name="program">
            /// </param>
            /// <param name="programInterface">
            /// </param>
            /// <param name="name">
            /// [length: COMPSIZE(name)]
            /// </param>
            [AutoGenerated(Category = "EXT_blend_func_extended", Version = "", EntryPoint = "glGetProgramResourceLocationIndexEXT")]
            public static int GetProgramResourceLocationIndex(uint program, OpenTK.Graphics.ES30.ProgramInterface programInterface, [CountAttribute(Computed = "name")] String name)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(17)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBindFragDataLocationEXT(uint program, uint color, [CountAttribute(Computed = "name")] IntPtr name);

            [Slot(18)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBindFragDataLocationIndexedEXT(uint program, uint colorNumber, uint index, IntPtr name);

            [Slot(264)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern int glGetFragDataIndexEXT(uint program, IntPtr name);

            [Slot(327)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern int glGetProgramResourceLocationIndexEXT(uint program, OpenTK.Graphics.ES30.ProgramInterface programInterface, [CountAttribute(Computed = "name")] IntPtr name);
        }
    }
}
