//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2015 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

using System;
using System.Text;
using System.Runtime.InteropServices;

namespace OpenTK.Graphics.OpenGL
{
    public sealed partial class GL
    {
        /// <summary>
        /// Contains native bindings to functions in the category "BlendFuncSeparate" in the extension "Ingr".
        /// </summary>
        public static partial class Ingr
        {
            /// <summary>
            /// [requires: INGR_blend_func_separate]
            /// Specify pixel arithmetic for RGB and alpha components separately
            /// </summary>
            /// <param name="sfactorRGB">
            /// For glBlendFuncSeparatei, specifies the index of the draw buffer for which to set the blend functions.
            /// </param>
            /// <param name="dfactorRGB">
            /// Specifies how the red, green, and blue blending factors are computed. The initial value is One.
            /// </param>
            /// <param name="sfactorAlpha">
            /// Specifies how the red, green, and blue destination blending factors are computed. The initial value is Zero.
            /// </param>
            /// <param name="dfactorAlpha">
            /// Specified how the alpha source blending factor is computed. The initial value is One.
            /// </param>
            [AutoGenerated(Category = "INGR_blend_func_separate", Version = "", EntryPoint = "glBlendFuncSeparateINGR")]
            public static void BlendFuncSeparate(OpenTK.Graphics.OpenGL.BlendingFactor sfactorRGB, OpenTK.Graphics.OpenGL.BlendingFactor dfactorRGB, OpenTK.Graphics.OpenGL.BlendingFactor sfactorAlpha, OpenTK.Graphics.OpenGL.BlendingFactor dfactorAlpha)
            {
                throw new BindingsNotRewrittenException();
            }

            [Slot(130)]
            [DllImport(Library, ExactSpelling = true, CallingConvention = CallingConvention.Winapi)]
            private static extern void glBlendFuncSeparateINGR(OpenTK.Graphics.OpenGL.BlendingFactor sfactorRGB, OpenTK.Graphics.OpenGL.BlendingFactor dfactorRGB, OpenTK.Graphics.OpenGL.BlendingFactor sfactorAlpha, OpenTK.Graphics.OpenGL.BlendingFactor dfactorAlpha);
        }
    }
}
